import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import ts from 'typescript';
import {build} from 'esbuild';
const schedule=ts.transpileModule(readFileSync('src/app/review-schedule.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {intervalFor,sortTopics}=await import('data:text/javascript;base64,'+Buffer.from(schedule).toString('base64'));
assert.equal(intervalFor(0,'good'),4);assert.equal(intervalFor(4,'good'),9);assert.equal(intervalFor(9,'good'),20);assert.equal(intervalFor(20,'again'),1);assert.equal(intervalFor(365,'easy'),365);
const topics=[{priority:'baixa',created_at:'2026-01-01',id:1},{priority:'alta',created_at:'2026-01-03',id:2},{priority:'alta',created_at:'2026-01-02',id:3}];assert.deepEqual(sortTopics(topics).map(x=>x.id),[3,2,1]);assert.equal(topics[0].id,1);
const memory=new Map();globalThis.__testScope='user-a';globalThis.__testUser=true;globalThis.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
globalThis.window={addEventListener(){},setInterval(){}};
let offline=true;const requests=[];globalThis.fetch=async (url,options)=>{if(offline)throw new Error('offline');requests.push({url,body:JSON.parse(options.body)});return new Response(null,{status:204})};
const compiled=await build({entryPoints:['src/app/sync.ts'],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'angular-test-signals',setup(b){b.onResolve({filter:/^\.\/account$/},()=>({path:'account',namespace:'accountmock'}));b.onLoad({filter:/.*/,namespace:'accountmock'},()=>({contents:`export const accountSession=()=>globalThis.__testUser?{user:{id:globalThis.__testScope}}:null;export const accountScope=()=>globalThis.__testScope;export const storageName=k=>'study:'+globalThis.__testScope+':'+k;export const supabase={rpc:(name,body)=>{const p=(async()=>{const res=await fetch('rpc/'+name,{body:JSON.stringify(body.payload)});return {error:res.ok?null:new Error('request failed')}})();p.abortSignal=()=>p;return p}};`}));b.onResolve({filter:/^@angular\/core$/},()=>({path:'core',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const signal=x=>{const s=()=>x;s.set=v=>x=v;return s}'}))}}]});
const sync=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
sync.write('study_queue?on_conflict=id',{id:'a',title:'offline topic'});await new Promise(r=>setTimeout(r,0));assert.equal(sync.hasPending(),true);assert.equal(JSON.parse(memory.get('study:user-a:study-pending-v1')).length,1);
sync.write('rpc/complete_study_topic',{topic_id:'a'});await new Promise(r=>setTimeout(r,0));assert.equal(JSON.parse(memory.get('study:user-a:study-pending-v1')).length,2);
offline=false;await sync.flush();assert.equal(sync.hasPending(),false);assert.equal(requests[0].body.title,'offline topic');assert.equal(requests[1].body.topic_id,'a');assert.equal(sync.syncStatus(),'Sincronizado');
// Rejecting a request must preserve it for retry; no silent data loss.
globalThis.fetch=async()=>new Response('temporary failure',{status:503});sync.write('seed_card_progress?on_conflict=card_id',{card_id:7,interval:9});await new Promise(r=>setTimeout(r,0));assert.equal(sync.hasPending(),true);globalThis.fetch=async()=>new Response(null,{status:204});await sync.flush();assert.equal(sync.hasPending(),false);
sync.cache('study-history',[{date:'2026-10-05'}]);globalThis.__testScope='user-b';assert.deepEqual(sync.cached('study-history',[]),[]);assert.equal(sync.hasPending(),false);sync.cache('study-history',[{date:'2026-10-06'}]);globalThis.__testScope='user-a';assert.equal(sync.cached('study-history',[])[0].date,'2026-10-05');globalThis.__testUser=false;sync.write('study_queue',{id:'local'});assert.equal(sync.hasPending(),false);assert.equal(sync.syncStatus(),'Salvo neste dispositivo');
const reminder=ts.transpileModule(readFileSync('src/app/reminders.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;const {calendarReminder}=await import('data:text/javascript;base64,'+Buffer.from(reminder).toString('base64'));const ics=calendarReminder('20:00',[1,3,5],new Date('2026-10-05T12:00:00Z'));assert.ok(ics.includes('RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR'));assert.ok(ics.includes('DTSTART;TZID=America/Sao_Paulo:20261005T200000'));assert.throws(()=>calendarReminder('25:00',[1]));assert.throws(()=>calendarReminder('20:00',[]));
// A recovery event must keep the password form open even if initial session loading finishes later.
globalThis.location={search:'',pathname:'/app-flash-card/',origin:'https://anamsilva1981.github.io'};globalThis.localStorage.removeItem=k=>memory.delete(k);globalThis.__authListener=null;
const sessionBuild=await build({entryPoints:['src/app/session.component.ts'],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'session-fixtures',setup(b){b.onResolve({filter:/^(@angular\/core|@angular\/forms|\.\/app\.component|\.\/app-icon\.component|\.\/account)$/},args=>({path:args.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='@angular/core'?'export const Component=()=>c=>c;export const signal=x=>{const s=()=>x;s.set=v=>x=v;return s}':args.path==='@angular/forms'?'export const FormsModule={}':args.path==='./app.component'?'export const AppComponent={}':args.path==='./app-icon.component'?'export const AppIconComponent={}':`let session=null;export const accountSession=()=>session;accountSession.set=v=>session=v;export const setScope=()=>{};export const supabase={auth:{onAuthStateChange:cb=>globalThis.__authListener=cb,getSession:()=>Promise.resolve({data:{session:{user:{id:'recovery-user'}}}})}};`}));}}]});
const {SessionComponent}=await import('data:text/javascript;base64,'+Buffer.from(sessionBuild.outputFiles[0].text).toString('base64'));const sessionPage=new SessionComponent();globalThis.__authListener('PASSWORD_RECOVERY',{user:{id:'recovery-user'}});assert.equal(sessionPage.mode(),'password');assert.equal(sessionPage.ready(),false);await new Promise(r=>setTimeout(r,0));assert.equal(sessionPage.mode(),'password');
const current=readFileSync('src/app/app.component.ts','utf8');const {execFileSync}=await import('node:child_process');const old=execFileSync('git',['show','HEAD:src/app/app.component.ts'],{encoding:'utf8'});const seed=s=>s.slice(s.indexOf(' private seed:'),s.indexOf(' cards=signal'));assert.equal(seed(current),seed(old));
assert.equal(existsSync('dist/app-flash-card/browser/ngsw.json'),false,'Service worker must remain disabled while rapid releases avoid stale PWA caches.');
console.log('Passed: progressive intervals, priorities, offline replay, retry after rejection, account cache isolation, local-only guest mode, calendar reminders, password recovery event ordering, original card preservation and disabled stale service-worker cache.');
