import { Component, computed, signal, OnInit } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatExpansionModule } from '@angular/material/expansion';
type Rating = 'again'|'hard'|'good'|'easy';
interface Card { id:number; subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'; topic:string; question:string; answer:string; explanation:string; example:string; due:string; interval:number; }
interface StudyDay { date:string; learning:string[]; reviews:string[]; }
const DAY=86400000;
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>new Date(Date.now()+n*DAY).toISOString().slice(0,10);
@Component({selector:'app-root',standalone:true,imports:[MatButtonModule,MatCardModule,MatChipsModule,MatExpansionModule],templateUrl:'./app.component.html',styleUrl:'./app.component.css'})
export class AppComponent implements OnInit {
 private readonly supabaseUrl='https://elzkhndhkkkfxvtbhilt.supabase.co';
 private readonly supabaseKey='sb_publishable_YFZqSuAst3q1ERiC3HA71A_u4fmIP9j';
 activeTab=signal<'home'|'progress'|'history'|'settings'>('home');
 subject=signal<'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java'|null>(null); topic=signal('Todos'); flipped=signal(false); explanationOpen=signal(false); index=signal(0);
 private seed:Card[]=[
 {id:1,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Quais são as etapas básicas para criar um modelo de ML?',answer:'Preparar dados, escolher algoritmo, treinar, avaliar e iterar.',explanation:'Um modelo de ML nasce dos dados. Primeiro os dados são coletados e preparados; depois escolhe-se um algoritmo adequado ao problema. O algoritmo é treinado para aprender padrões nesses dados. Em seguida, o modelo é avaliado com dados de teste para verificar se generaliza bem. Se o resultado não for satisfatório, ajustam-se dados, algoritmo ou parâmetros e o processo é repetido.',example:"Exemplo: para reconhecer gatos e cachorros, você prepara as fotos, escolhe o algoritmo, treina, testa e ajusta o modelo.",due:today(),interval:0},
 {id:2,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Por que a qualidade dos dados de treinamento é tão importante?',answer:'Dados ruins geram modelos e previsões ruins.',explanation:'A qualidade do modelo depende diretamente da informação usada no treinamento. Dados incorretos, incompletos, enviesados ou mal preparados fazem o algoritmo aprender padrões errados. Mesmo um algoritmo excelente não corrige automaticamente dados ruins. Por isso, coleta, limpeza e preparação são etapas críticas. É a ideia de “garbage in, garbage out”: entrada ruim tende a produzir saída ruim.',example:"Exemplo: se várias fotos de gatos estiverem rotuladas como “cachorro”, o modelo pode aprender a classificação errada.",due:today(),interval:0},
 {id:3,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que são dados rotulados?',answer:'Dados que possuem uma saída ou classe conhecida associada.',explanation:'Dados rotulados possuem, além das características de entrada, a resposta correta associada a cada exemplo. Por exemplo, uma transação pode vir acompanhada do rótulo “fraude” ou “não fraude”. Durante o treinamento supervisionado, o modelo compara suas previsões com esses rótulos. Assim, ele aprende a relação entre as entradas e a saída esperada para depois prever casos novos.',example:"Exemplo: uma foto já marcada como “gato” ou “cachorro” vem acompanhada da resposta que o modelo deve aprender.",due:today(),interval:0},
 {id:4,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que são dados não rotulados?',answer:'Dados de entrada sem saída, classe ou variável-alvo associada.',explanation:'Dados não rotulados contêm exemplos sem uma resposta correta previamente informada. O conjunto pode ter características de clientes, produtos ou transações, mas não diz a qual grupo cada item pertence. Esses dados são comuns em aprendizado não supervisionado. O modelo procura estruturas, semelhanças ou agrupamentos existentes nos próprios dados, em vez de aprender a partir de uma variável-alvo conhecida.',example:"Exemplo: você tem dados de clientes sem informar grupos; o algoritmo tenta descobrir sozinho quais clientes são parecidos.",due:today(),interval:0},
 {id:5,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que caracteriza dados não estruturados?',answer:'Não possuem formato predefinido, como texto, imagem, áudio e vídeo.',explanation:'Dados não estruturados não seguem naturalmente um esquema fixo de linhas e colunas. Texto livre, imagens, áudio e vídeo são exemplos comuns. Eles possuem informação, mas ela não está organizada em campos predefinidos como numa tabela. Para serem usados em ML, normalmente precisam de processamento que transforme seu conteúdo em uma representação que o algoritmo consiga analisar.',example:"Exemplo: uma planilha tem colunas definidas; já fotos, áudios e textos livres não seguem esse formato tabular.",due:today(),interval:0},
 {id:6,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual tipo de aprendizado utiliza dados rotulados?',answer:'Aprendizado supervisionado.',explanation:'No aprendizado supervisionado, o modelo aprende usando exemplos que já possuem a resposta correta, ou seja, dados rotulados. Ele observa entradas e respectivos rótulos durante o treinamento e aprende uma função capaz de relacioná-los. Classificação e regressão são problemas típicos desse paradigma. Depois do treinamento, o objetivo é prever corretamente a saída de exemplos que o modelo nunca viu.',example:"Exemplo: e-mails já marcados como “spam” ou “não spam” podem treinar um classificador supervisionado.",due:today(),interval:0},
 {id:7,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual é o objetivo do aprendizado supervisionado?',answer:'Aprender a prever a saída para dados novos e ainda não vistos.',explanation:'O aprendizado supervisionado não busca apenas memorizar os exemplos de treinamento. O objetivo é aprender padrões que possam ser generalizados para dados novos. Por isso, o desempenho precisa ser avaliado em exemplos que não foram usados para ensinar o modelo. Se ele funciona apenas nos dados de treinamento, pode estar ocorrendo overfitting e seu desempenho real será ruim.',example:"Exemplo: depois de treinar com compras antigas, o modelo tenta prever o risco de uma compra nova que nunca viu.",due:today(),interval:0},
 {id:8,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual tipo de aprendizado utiliza dados não rotulados?',answer:'Aprendizado não supervisionado.',explanation:'No aprendizado não supervisionado, os dados não possuem rótulos indicando a resposta correta. O algoritmo analisa as características disponíveis e tenta descobrir estrutura por conta própria. Um exemplo é agrupar clientes com comportamentos semelhantes sem informar previamente quais grupos existem. Clustering e algumas técnicas de redução de dimensionalidade são aplicações comuns desse tipo de aprendizado.',example:"Exemplo: um algoritmo pode separar clientes em grupos de comportamento sem receber previamente o nome desses grupos.",due:today(),interval:0},
 {id:9,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Como funciona o aprendizado por reforço?',answer:'O modelo aprende com recompensas e penalidades por suas ações.',explanation:'No aprendizado por reforço, um agente interage com um ambiente e toma ações. Conforme as consequências dessas ações, recebe recompensas ou penalidades. Ao repetir esse processo, aprende uma estratégia que busca maximizar a recompensa acumulada. Diferentemente do supervisionado, ele não recebe simplesmente uma resposta correta para cada exemplo; aprende com as consequências de suas decisões.',example:"Exemplo: em um jogo, o agente ganha pontos por boas jogadas e perde por ruins, ajustando sua estratégia com o tempo.",due:today(),interval:0},
 {id:10,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual a diferença entre inferência em lote e em tempo real?',answer:'Lote processa vários dados juntos; tempo real responde quase imediatamente.',explanation:'Inferência é o uso de um modelo já treinado para gerar previsões. Na inferência em lote, vários registros são reunidos e processados de uma vez, sendo adequada quando a resposta não precisa ser imediata. Na inferência em tempo real, cada solicitação precisa receber uma previsão com baixa latência. A escolha depende principalmente da necessidade de velocidade e do padrão de uso.',example:"Exemplo: processar 100 mil registros à noite é lote; responder a uma compra suspeita em milissegundos é tempo real.",due:today(),interval:0},
 {id:11,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Em quais duas categorias os tipos de JavaScript se dividem?',answer:'Tipos primitivos e tipos de objeto.',explanation:'JavaScript separa seus valores em tipos primitivos e objetos. Os primitivos representam valores básicos e são imutáveis. Objetos são estruturas que podem reunir propriedades e outros valores e, em geral, são mutáveis. Arrays e funções também pertencem ao universo dos objetos. Essa distinção ajuda a entender como valores se comportam quando são manipulados pelo programa.',example:"Exemplo: 42 e “Ana” são primitivos; { nome: “Ana” } é um objeto.",due:today(),interval:0},
 {id:12,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Quais são os tipos primitivos de JavaScript?',answer:'Números, strings, booleanos, null, undefined e símbolos.',explanation:'Os tipos primitivos básicos estudados são number, string, boolean, null, undefined e symbol. Eles representam valores simples e não são objetos. Uma característica importante é que seus valores são imutáveis. Mesmo quando parece que alteramos uma string ou um número, na prática produzimos ou atribuímos outro valor, em vez de modificar internamente o valor primitivo existente.',example:"Exemplo: 10 é number, “oi” é string, true é boolean, null e undefined representam ausência, e Symbol cria identificadores únicos.",due:today(),interval:0},
 {id:13,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Qual é a principal característica dos valores primitivos?',answer:'São imutáveis: não podem ser alterados.',explanation:'Imutabilidade significa que o próprio valor primitivo não pode ser modificado depois de criado. Se uma variável contém um valor e recebe outro, quem muda é a associação da variável, não o valor original. Isso contrasta com objetos, cujas propriedades podem ser alteradas mantendo o mesmo objeto. Essa diferença é fundamental para entender atribuições e manipulação de dados em JavaScript.',example:"Exemplo: ao fazer let x = 10 e depois x = 20, você troca o valor da variável; o número 10 não foi alterado.",due:today(),interval:0},
 {id:14,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Strings são mutáveis ou imutáveis?',answer:'Imutáveis. Uma string existente não pode ser alterada.',explanation:'Strings são valores primitivos e, portanto, são imutáveis. Métodos podem produzir uma nova string, mas não alteram os caracteres da string original. Por exemplo, transformar um texto em maiúsculas resulta em outro valor. A variável pode então receber esse novo valor, dando a impressão de alteração, mas a string original em si não foi modificada.',example:"Exemplo: “ana”.toUpperCase() produz “ANA”; a string original “ana” continua sendo outro valor.",due:today(),interval:0},
 {id:15,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que é um objeto em JavaScript?',answer:'Uma coleção de propriedades, cada uma com nome e valor.',explanation:'Um objeto é uma coleção de propriedades. Cada propriedade possui um nome e um valor, permitindo reunir informações relacionadas numa única estrutura. O valor de uma propriedade pode ser de diferentes tipos, inclusive outro objeto. Diferentemente dos valores primitivos, objetos são mutáveis: suas propriedades podem ser adicionadas, removidas ou alteradas sem criar necessariamente um novo objeto.',example:"Exemplo: { nome: “Ana”, idade: 44 } reúne duas propriedades dentro do mesmo objeto.",due:today(),interval:0},
 {id:16,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Objetos são mutáveis. O que isso significa?',answer:'Suas propriedades podem ser alteradas.',explanation:'Dizer que objetos são mutáveis significa que seu conteúdo pode mudar depois que o objeto foi criado. É possível alterar o valor de uma propriedade, adicionar uma nova ou remover uma existente. O objeto continua sendo a mesma estrutura de referência. Essa característica diferencia objetos dos valores primitivos, cujo próprio conteúdo não pode ser alterado.',example:"Exemplo: em usuario.idade = 45, a propriedade muda sem precisar criar outro objeto.",due:today(),interval:0},
 {id:17,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que é um array em JavaScript?',answer:'Um objeto que representa uma coleção ordenada de valores.',explanation:'Um array é um tipo de objeto usado para representar uma coleção ordenada de valores. Cada elemento ocupa uma posição identificada por um índice, normalmente começando em zero. Arrays podem guardar valores de diferentes tipos e seu conteúdo pode ser alterado. Por serem objetos, também possuem propriedades e métodos usados para trabalhar com suas coleções.',example:"Exemplo: ['Angular', 'React'] é um array; Angular está no índice 0 e React no índice 1.",due:today(),interval:0},
 {id:18,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que são métodos em JavaScript?',answer:'Funções associadas a valores ou objetos.',explanation:'Métodos são funções associadas a valores ou objetos e são chamadas por meio deles. Eles permitem executar operações relacionadas àquele valor, como manipular uma string ou trabalhar com elementos de um array. Embora valores primitivos não sejam objetos, JavaScript permite acessar diversos métodos neles por mecanismos internos da linguagem. null e undefined são exceções importantes.',example:"Exemplo: 'ana'.toUpperCase() chama o método toUpperCase para produzir uma nova string.",due:today(),interval:0},
 {id:19,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Quais valores não permitem invocar métodos?',answer:'null e undefined.',explanation:'null e undefined são valores especiais que não permitem invocar métodos diretamente. undefined normalmente representa ausência de um valor atribuído, enquanto null é usado para representar intencionalmente ausência de valor. Tentar acessar uma propriedade ou chamar um método diretamente nesses valores causa erro. Por isso, é comum verificar se um valor existe antes de utilizá-lo.',example:"Exemplo: tentar executar null.toString() ou undefined.toString() gera erro.",due:today(),interval:0},
 {id:20,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Qual é a diferença entre const, let e var?',answer:'const declara constantes; let e var declaram variáveis.',explanation:'const é usado quando a variável não deve receber uma nova atribuição; let permite reatribuição e possui escopo de bloco. var é uma forma mais antiga de declarar variáveis e possui regras de escopo diferentes. Importante: const não torna um objeto imutável. Um objeto declarado com const ainda pode ter suas propriedades alteradas; o que não pode mudar é a referência atribuída à variável.',example:"Exemplo: let contador = 1 pode virar 2; const usuario não pode receber outro objeto, mas usuario.nome pode mudar.",due:today(),interval:0},

 {id:21,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões de projeto?',answer:'Soluções típicas e reutilizáveis para problemas comuns de projeto de software.',explanation:'Padrões de projeto são modelos de solução para problemas recorrentes no design de software. Eles não são códigos prontos que devem ser copiados, mas estruturas gerais que podem ser adaptadas ao contexto da aplicação. Funcionam como uma planta: mostram uma forma conhecida de organizar classes e objetos para resolver determinado problema de projeto.',example:"Exemplo: o padrão Observer resolve de forma reutilizável o problema de avisar vários objetos quando um estado muda.",due:today(),interval:0},
 {id:22,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'Como os padrões de projeto podem ser classificados?',answer:'Por complexidade, nível de detalhes, escala de aplicação e propósito.',explanation:'Os padrões variam desde soluções pequenas, ligadas a detalhes de uma linguagem, até decisões que influenciam a arquitetura de uma aplicação inteira. Além dessa escala, eles também podem ser classificados pela intenção do problema que resolvem. Nessa classificação por propósito, os grupos principais são criacionais, estruturais e comportamentais.',example:"Exemplo: um padrão de criação atua em uma parte do código; um padrão arquitetônico pode organizar a aplicação inteira.",due:today(),interval:0},
 {id:23,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões idiomáticos?',answer:'Padrões básicos e de baixo nível, geralmente específicos de uma linguagem.',explanation:'Padrões idiomáticos ficam mais próximos dos detalhes de implementação. Eles normalmente exploram características próprias de uma linguagem de programação e, por isso, não são necessariamente transferíveis para outra linguagem. Sua escala de aplicação é menor do que a dos padrões arquitetônicos.',example:"Exemplo: um idiom em JavaScript pode explorar recursos específicos da linguagem, como closures, para organizar uma solução.",due:today(),interval:0},
 {id:24,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões arquitetônicos?',answer:'Padrões de alto nível usados para projetar a arquitetura de uma aplicação.',explanation:'Padrões arquitetônicos trabalham em uma escala maior e podem orientar a organização de uma aplicação inteira. Por serem mais universais, podem ser implementados em diferentes linguagens. Eles tratam da estrutura geral do sistema, enquanto padrões de menor nível normalmente resolvem problemas mais localizados.',example:"Exemplo: MVC ou arquitetura em camadas orientam a estrutura geral do sistema, não apenas uma classe isolada.",due:today(),interval:0},
 {id:25,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'Quais são os três grupos de padrões por propósito?',answer:'Criacionais, estruturais e comportamentais.',explanation:'Quando classificados pela intenção, os padrões são divididos em três grandes grupos. Os criacionais tratam da criação de objetos. Os estruturais tratam da composição de classes e objetos em estruturas maiores. Os comportamentais tratam da comunicação e da distribuição de responsabilidades entre objetos.',example:"Exemplo: Factory é criacional, Adapter é estrutural e Observer é comportamental.",due:today(),interval:0},
 {id:26,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que são padrões criacionais?',answer:'Mecanismos de criação de objetos que aumentam flexibilidade e reutilização.',explanation:'Padrões criacionais organizam a maneira como objetos são criados. A ideia é reduzir o acoplamento entre o código que precisa de um objeto e os detalhes de sua construção. Isso torna o sistema mais flexível quando a forma de criação muda e facilita reutilizar soluções de construção em diferentes partes da aplicação.',example:"Exemplo: uma Factory pode decidir qual classe de pagamento criar sem expor essa decisão ao código que vai usá-la.",due:today(),interval:0},
 {id:27,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'Quais são os padrões criacionais?',answer:'Factory Method, Abstract Factory, Builder, Prototype e Singleton.',explanation:'Os padrões criacionais são padrões relacionados à criação de objetos. Eles ajudam a tornar a criação mais flexível e reduzem o acoplamento entre o código que utiliza o objeto e a forma como ele é criado.',example:"Exemplo: Factory escolhe o objeto a criar; Builder monta um objeto complexo passo a passo; Singleton mantém uma única instância.",due:today(),interval:0},
 {id:28,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que são padrões estruturais?',answer:'Formas de compor classes e objetos em estruturas maiores, flexíveis e eficientes.',explanation:'Padrões estruturais tratam de como classes e objetos podem ser conectados para formar estruturas maiores sem perder flexibilidade. Eles ajudam a organizar relações entre componentes, adaptar interfaces e adicionar responsabilidades sem tornar a estrutura desnecessariamente rígida.',example:"Exemplo: um Adapter pode fazer uma API antiga funcionar com a interface esperada pelo código novo.",due:today(),interval:0},
 {id:29,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'Quais são os padrões estruturais?',answer:'Adapter, Bridge, Composite, Decorator, Facade, Flyweight e Proxy.',explanation:'O grupo estrutural contém sete padrões clássicos: Adapter, Bridge, Composite, Decorator, Facade, Flyweight e Proxy. Apesar de resolverem problemas diferentes, todos se concentram em como classes e objetos são combinados e organizados para formar estruturas maiores.',example:"Exemplo: uma Facade oferece uma entrada simples para um conjunto complexo de serviços internos.",due:today(),interval:0},
 {id:30,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que são padrões comportamentais?',answer:'Padrões para comunicação eficiente e distribuição de responsabilidades entre objetos.',explanation:'Padrões comportamentais se concentram na interação entre objetos. Eles ajudam a definir quem executa determinada responsabilidade, como uma solicitação percorre o sistema e como diferentes objetos colaboram sem ficarem excessivamente acoplados uns aos outros.',example:"Exemplo: no Observer, vários componentes podem ser avisados automaticamente quando um dado observado muda.",due:today(),interval:0},
 {id:31,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'Quais são os padrões comportamentais?',answer:'Chain of Responsibility, Command, Iterator, Mediator, Memento, Observer, State, Strategy, Template Method e Visitor.',explanation:'O catálogo apresenta dez padrões comportamentais: Chain of Responsibility, Command, Iterator, Mediator, Memento, Observer, State, Strategy, Template Method e Visitor. Eles tratam principalmente de comunicação, fluxo de responsabilidades e colaboração entre objetos.',example:"Exemplo: Strategy troca um algoritmo em runtime, Observer notifica interessados e Command encapsula uma ação.",due:today(),interval:0}
 ];
 cards=signal<Card[]>(this.load());
 history=signal<StudyDay[]>(this.loadHistory());
 private learningSeed:StudyDay[]=[{date:'2026-10-02',learning:['JavaScript — 3.1 — Visão geral e definições','AWS IA — Fundamentos de Machine Learning','Padrões de Projeto — Classificação dos padrões'],reviews:[]}];
 ngOnInit(){void this.loadRemoteHistory();}
 private async api(path:string,options:RequestInit={}){return fetch(this.supabaseUrl+'/rest/v1/'+path,{...options,headers:{apikey:this.supabaseKey,Authorization:'Bearer '+this.supabaseKey,'Content-Type':'application/json',Prefer:'return=minimal',...(options.headers||{})}})}
 private async loadRemoteHistory(){try{const res=await this.api('study_activity?select=activity_date,kind,label&order=activity_date.desc,created_at.asc');if(!res.ok)return;const rows:any[]=await res.json();const days=new Map<string,StudyDay>();for(const row of rows){if(!days.has(row.activity_date))days.set(row.activity_date,{date:row.activity_date,learning:[],reviews:[]});const day=days.get(row.activity_date)!;const target=row.kind==='learning'?day.learning:day.reviews;if(!target.includes(row.label))target.push(row.label);}this.history.set(this.mergeLearning([...days.values()]));}catch{}}
 private loadHistory():StudyDay[]{return this.learningSeed;}
 private mergeLearning(saved:StudyDay[]):StudyDay[]{const result=saved.map(d=>({...d,learning:[...d.learning],reviews:[...d.reviews]}));for(const seedDay of this.learningSeed){const found=result.find(d=>d.date===seedDay.date);if(found){found.learning=Array.from(new Set([...found.learning,...seedDay.learning]));}else result.push({...seedDay,learning:[...seedDay.learning],reviews:[]});}return result.sort((a,b)=>b.date.localeCompare(a.date));}
 private saveReview(label:string){const date=today();const next=this.history().map(d=>({...d,learning:[...d.learning],reviews:[...d.reviews]}));let day=next.find(d=>d.date===date);if(!day){day={date,learning:[],reviews:[]};next.push(day);}if(!day.reviews.includes(label))day.reviews.push(label);next.sort((a,b)=>b.date.localeCompare(a.date));this.history.set(next);void this.api('study_activity?on_conflict=activity_date,kind,label',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({activity_date:date,kind:'review',label})});}
 reviewLabel(){const subject=this.subject();const topic=this.topic();const name=subject==='AWS'?'AWS IA':subject||'';return topic==='Todos'?name:`${name} — ${topic}`;}
 formatDate(date:string){const [y,m,d]=date.split('-');return `${d}/${m}/${y}`;}
 subjectCards=computed(()=>this.subject()?this.cards().filter(c=>c.subject===this.subject()):[]);
 topics=computed(()=>['Todos',...Array.from(new Set(this.subjectCards().map(c=>c.topic)))]);
 dueCards=computed(()=>this.shuffle(this.subjectCards().filter(c=>c.due<=today()&&(this.topic()==='Todos'||c.topic===this.topic()))));
 totalDue=computed(()=>this.cards().filter(c=>c.due<=today()).length);
 subjectDue=(subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java')=>this.cards().filter(c=>c.subject===subject&&c.due<=today()).length;
 subjectTotal=(subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java')=>this.cards().filter(c=>c.subject===subject).length;
 subjectIcon(subject:string){return ({AWS:'☁',JavaScript:'JS','Padrões de Projeto':'▱',Angular:'A',React:'⚛',Arquitetura:'⌂',Java:'☕'} as Record<string,string>)[subject]||'•';}
 setTab(tab:'home'|'progress'|'history'|'settings'){this.activeTab.set(tab);}
 card=computed(()=>this.dueCards()[this.index()%Math.max(this.dueCards().length,1)]);
 progress=computed(()=>this.dueCards().length?String(this.index()+1)+' / '+String(this.dueCards().length):'0 / 0');
 private shuffle<T>(items:T[]):T[]{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
 private load():Card[]{try{
  const saved:Card[]=JSON.parse(localStorage.getItem('flashcards')||'null');
  if(!Array.isArray(saved))return this.seed;
  return this.seed.map(seedCard=>{
   const previous=saved.find(card=>card.question===seedCard.question);
   return previous?{...seedCard,due:previous.due,interval:previous.interval}:seedCard;
  });
 }catch{return this.seed}}
 openSubject(v:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java'){this.subject.set(v);this.topic.set('Todos');this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
 back(){this.subject.set(null);this.topic.set('Todos');this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false);this.activeTab.set('home')}
 choose(v:string){this.topic.set(v);this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
 reveal(){this.flipped.set(!this.flipped());this.explanationOpen.set(false)}
 toggleExplanation(){this.explanationOpen.set(!this.explanationOpen())}
 rate(r:Rating){const c=this.card();if(!c)return;const days={again:1,hard:2,good:4,easy:7}[r];const currentDeck=this.dueCards().map(x=>x.id);this.cards.set(this.cards().map(x=>x.id===c.id?{...x,due:addDays(days),interval:days}:x));localStorage.setItem('flashcards',JSON.stringify(this.cards()));const remaining=this.cards().filter(x=>currentDeck.includes(x.id)&&x.due<=today()).length;if(remaining===0)this.saveReview(this.reviewLabel());this.flipped.set(false);this.explanationOpen.set(false);this.index.set(0)}
 reset(){localStorage.removeItem('flashcards');this.cards.set(this.seed);this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
}