import { Component, computed, signal, OnInit, HostListener, ViewChild } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatExpansionModule } from '@angular/material/expansion';
import { SubjectManagerComponent } from './subject-manager.component';
type Rating = 'again'|'hard'|'good'|'easy';
interface Card { id:number; subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'; topic:string; question:string; answer:string; explanation:string; example:string; due:string; interval:number; }
interface StudyDay { date:string; learning:string[]; reviews:string[]; }
interface StudyItem { id:string; title:string; subject:string; notes:string; link:string; priority:'baixa'|'media'|'alta'; status:'todo'|'done'; completed_at:string|null; }
const DAY=86400000;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
const addDays=(n:number)=>new Date(Date.now()+n*DAY).toISOString().slice(0,10);
@Component({selector:'app-root',standalone:true,imports:[SubjectManagerComponent,MatButtonModule,MatCardModule,MatChipsModule,MatExpansionModule],templateUrl:'./app.component.html',styleUrl:'./app.component.css'})
export class AppComponent implements OnInit {
 private readonly supabaseUrl='https://elzkhndhkkkfxvtbhilt.supabase.co';
 private readonly supabaseKey='sb_publishable_YFZqSuAst3q1ERiC3HA71A_u4fmIP9j';
 activeTab=signal<'home'|'studyPlan'|'progress'|'history'|'settings'>('home');
 studyItems=signal<StudyItem[]>([]); studySubjects=signal<string[]>(['AWS IA','JavaScript','Padrões de Projeto','Angular','React','Arquitetura','Java']); studyFormOpen=signal(false); studyTitle=signal(''); studySubject=signal('JavaScript'); studyNotes=signal(''); studyLink=signal(''); studyPriority=signal<'baixa'|'media'|'alta'>('media'); editingStudyId=signal<string|null>(null); subjectFormOpen=signal(false); newSubjectName=signal('');
 historyMonth=signal(new Date(today()+'T12:00:00'));
 selectedHistoryDate=signal<string|null>(null);
 subject=signal<'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java'|null>(null); topic=signal('Todos'); flipped=signal(false); explanationOpen=signal(false); index=signal(0);
 private seed:Card[]=[
 {id:1,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Quais são as etapas básicas para criar um modelo de ML?',answer:'Preparar dados, escolher algoritmo, treinar, avaliar e iterar.',explanation:'Um modelo de ML nasce dos dados. Primeiro os dados são coletados e preparados; depois escolhe-se um algoritmo adequado ao problema. O algoritmo é treinado para aprender padrões nesses dados. Em seguida, o modelo é avaliado com dados de teste para verificar se generaliza bem. Se o resultado não for satisfatório, ajustam-se dados, algoritmo ou parâmetros e o processo é repetido.',example:"Exemplo: para reconhecer gatos e cachorros, você prepara as fotos, escolhe o algoritmo, treina, testa e ajusta o modelo.",due:today(),interval:0},
 {id:2,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Por que a qualidade dos dados de treinamento é tão importante?',answer:'Dados ruins geram modelos e previsões ruins.',explanation:'A qualidade do modelo depende diretamente da informação usada no treinamento. Dados incorretos, incompletos, enviesados ou mal preparados fazem o algoritmo aprender padrões errados. Mesmo um algoritmo excelente não corrige automaticamente dados ruins. Por isso, coleta, limpeza e preparação são etapas críticas. É a ideia de “garbage in, garbage out”: entrada ruim tende a produzir saída ruim.',example:"Exemplo: se várias fotos de gatos estiverem rotuladas como “cachorro”, o modelo pode aprender a classificação errada.",due:today(),interval:0},
 {id:3,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que são dados rotulados?',answer:'Dados que possuem uma saída ou classe conhecida associada.',explanation:'Dados rotulados possuem, além das características de entrada, a resposta correta associada a cada exemplo. Por exemplo, uma transação pode vir acompanhada do rótulo “fraude” ou “não fraude”. Durante o treinamento supervisionado, o modelo compara suas previsões com esses rótulos. Assim, ele aprende a relação entre as entradas e a saída esperada para depois prever casos novos.',example:"Exemplo: uma foto já marcada como “gato” ou “cachorro” vem acompanhada da resposta que o modelo deve aprender.",due:today(),interval:0},
 {id:4,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que são dados não rotulados?',answer:'Dados de entrada sem saída, classe ou variável-alvo associada.',explanation:'Dados não rotulados contêm exemplos sem uma resposta correta previamente informada. O conjunto pode ter características de clientes, produtos ou transações, mas não diz a qual grupo cada item pertence. Esses dados são comuns em aprendizado não supervisionado. O modelo procura estruturas, semelhanças ou agrupamentos existentes nos próprios dados, em vez de aprender a partir de uma variável-alvo conhecida.',example:"Exemplo: você tem dados de clientes sem informar grupos; o algoritmo tenta descobrir sozinho quais clientes são parecidos.",due:today(),interval:0},
 {id:5,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'O que caracteriza dados não estruturados?',answer:'Não possuem formato predefinido, como texto, imagem, áudio e vídeo.',explanation:'Dados não estruturados não seguem naturalmente um esquema fixo de linhas e colunas. Texto livre, imagens, áudio e vídeo são exemplos comuns. Eles possuem informação, mas ela não está organizada em campos predefinidos como numa tabela. Para serem usados em ML, normalmente precisam de processamento que transforme seu conteúdo em uma representação que o algoritmo consiga analisar.',example:"Exemplo: uma planilha tem colunas definidas; já fotos, áudios e textos livres não seguem esse formato tabular.",due:today(),interval:0},
 {id:6,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual tipo de aprendizado utiliza dados rotulados?',answer:'Aprendizado supervisionado.',explanation:'No aprendizado supervisionado, o modelo aprende usando exemplos que já possuem a resposta correta, ou seja, dados rotulados. Ele observa entradas e respectivos rótulos durante o treinamento e aprende uma função capaz de relacioná-los. Classificação e regressão são problemas típicos desse paradigma. Depois do treinamento, o objetivo é prever corretamente a saída de exemplos que o modelo nunca viu.',example:"Exemplo: e-mails já marcados como “spam” ou “não spam” podem treinar um classificador supervisionado.",due:today(),interval:0},
 {id:7,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual é o objetivo do aprendizado supervisionado?',answer:'Aprender a prever a saída para dados novos e ainda não vistos.',explanation:'O aprendizado supervisionado não busca apenas memorizar os exemplos de treinamento. O objetivo é aprender padrões que possam ser generalizados para dados novos. Por isso, o desempenho precisa ser avaliado em exemplos que não foram usados para ensinar o modelo. Se ele funciona apenas nos dados de treinamento, pode estar ocorrendo overfitting e seu desempenho real será ruim.',example:"Exemplo: depois de treinar com compras antigas, o modelo tenta prever o risco de uma compra nova que nunca viu.",due:today(),interval:0},
 {id:8,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual tipo de aprendizado utiliza dados não rotulados?',answer:'Aprendizado não supervisionado.',explanation:'No aprendizado não supervisionado, os dados não possuem rótulos indicando a resposta correta. O algoritmo analisa as características disponíveis e tenta descobrir estrutura por conta própria. Um exemplo é agrupar clientes com comportamentos semelhantes sem informar previamente quais grupos existem. Clustering e algumas técnicas de redução de dimensionalidade são aplicações comuns desse tipo de aprendizado.',example:"Exemplo: um algoritmo pode separar clientes em grupos de comportamento sem receber previamente o nome desses grupos.",due:today(),interval:0},
 {id:9,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Como funciona o aprendizado por reforço?',answer:'O modelo aprende com recompensas e penalidades por suas ações.',explanation:'No aprendizado por reforço, um agente interage com um ambiente e toma ações. Conforme as consequências dessas ações, recebe recompensas ou penalidades. Ao repetir esse processo, aprende uma estratégia que busca maximizar a recompensa acumulada. Diferentemente do supervisionado, ele não recebe simplesmente uma resposta correta para cada exemplo; aprende com as consequências de suas decisões.',example:"Exemplo: em um jogo, o agente ganha pontos por boas jogadas e perde por ruins, ajustando sua estratégia com o tempo.",due:today(),interval:0},
 {id:10,subject:'AWS',topic:'Fundamentos de Machine Learning',question:'Qual a diferença entre inferência em lote e em tempo real?',answer:'Lote processa vários dados juntos; tempo real responde quase imediatamente.',explanation:'Inferência é o uso de um modelo já treinado para gerar previsões. Na inferência em lote, vários registros são reunidos e processados de uma vez, sendo adequada quando a resposta não precisa ser imediata. Na inferência em tempo real, cada solicitação precisa receber uma previsão com baixa latência. A escolha depende principalmente da necessidade de velocidade e do padrão de uso.',example:"Exemplo: processar 100 mil registros à noite é lote; responder a uma compra suspeita em milissegundos é tempo real.",due:today(),interval:0},
 {id:122,subject:'AWS',topic:'IA Responsável',question:'O que fazer ao identificar viés em um modelo de IA?',answer:'Identificar a causa e mitigar o viés para reduzir resultados injustos.',explanation:'Viés acontece quando o modelo aprende ou reproduz padrões que favorecem ou prejudicam pessoas ou grupos de forma indevida. O trabalho não termina ao detectar o problema: é preciso investigar de onde ele vem e agir para reduzi-lo. Mesmo retirando um dado sensível, outras informações podem funcionar como proxies e recriar o viés indiretamente.',example:'Exemplo: um modelo não usa gênero, mas usa dados correlacionados que acabam prejudicando sistematicamente um grupo; a equipe precisa detectar e mitigar esse efeito.',due:today(),interval:0},
 {id:123,subject:'AWS',topic:'IA Responsável',question:'Qual a diferença entre equidade e robustez em IA?',answer:'Equidade busca tratamento justo; robustez mantém o modelo confiável diante de variações.',explanation:'Equidade está ligada a evitar resultados injustamente diferentes entre pessoas ou grupos comparáveis. Robustez é a capacidade do modelo de continuar produzindo resultados confiáveis quando os dados variam, têm ruído ou apresentam situações um pouco diferentes das vistas no treinamento. Um modelo pode ser robusto e ainda assim não ser justo.',example:'Exemplo: um modelo de crédito robusto não muda de decisão por uma pequena oscilação de renda; para ser justo, também não deve prejudicar um grupo específico sem razão relevante.',due:today(),interval:0},
 {id:124,subject:'AWS',topic:'IA Responsável',question:'Por que um modelo de IA precisa de monitoramento contínuo?',answer:'Para detectar mudanças, erros ou perda de desempenho e permitir melhoria contínua.',explanation:'Um modelo pode funcionar bem quando é lançado e piorar com o tempo porque os dados, o ambiente ou o comportamento dos usuários mudam. Monitorar significa acompanhar métricas e resultados para perceber esses desvios e agir. O objetivo não é apenas encontrar problemas, mas corrigir, ajustar ou retreinar o modelo quando necessário.',example:'Exemplo: um modelo de seguros começa a errar após surgirem novos perfis de sinistro; o monitoramento detecta a queda e indica que o modelo precisa ser ajustado.',due:today(),interval:0},
 {id:125,subject:'AWS',topic:'IA Responsável',question:'Como explicabilidade, transparência e responsabilidade se relacionam?',answer:'Explicar decisões, tornar o processo claro e assumir responsabilidade pelos impactos.',explanation:'Explicabilidade é conseguir dizer por que uma decisão foi tomada. Transparência é deixar claros os processos, dados, critérios e limitações relevantes. Responsabilidade significa existir governança e pessoas ou organizações que respondam pelos impactos do uso da IA. Juntas, essas práticas aumentam confiança e permitem contestar ou auditar decisões.',example:'Exemplo: ao negar crédito, a empresa deve conseguir explicar os fatores relevantes, documentar como o sistema funciona e assumir responsabilidade pela decisão e seus impactos.',due:today(),interval:0},
 {id:11,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Em quais duas categorias os tipos de JavaScript se dividem?',answer:'Tipos primitivos e tipos de objeto.',explanation:'JavaScript separa seus valores em tipos primitivos e objetos. Os primitivos representam valores básicos e são imutáveis. Objetos são estruturas que podem reunir propriedades e outros valores e, em geral, são mutáveis. Arrays e funções também pertencem ao universo dos objetos. Essa distinção ajuda a entender como valores se comportam quando são manipulados pelo programa.',example:"Exemplo: 42 e “Ana” são primitivos; { nome: “Ana” } é um objeto.",due:today(),interval:0},
 {id:12,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Quais são os tipos primitivos de JavaScript?',answer:'Números, strings, booleanos, null, undefined e símbolos.',explanation:'Os tipos primitivos básicos estudados são number, string, boolean, null, undefined e symbol. Eles representam valores simples e não são objetos. Uma característica importante é que seus valores são imutáveis. Mesmo quando parece que alteramos uma string ou um número, na prática produzimos ou atribuímos outro valor, em vez de modificar internamente o valor primitivo existente.',example:"Exemplo: 10 é number, “oi” é string, true é boolean, null e undefined representam ausência, e Symbol cria identificadores únicos.",due:today(),interval:0},
 {id:13,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Qual é a principal característica dos valores primitivos?',answer:'São imutáveis: não podem ser alterados.',explanation:'Imutabilidade significa que o próprio valor primitivo não pode ser modificado depois de criado. Se uma variável contém um valor e recebe outro, quem muda é a associação da variável, não o valor original. Isso contrasta com objetos, cujas propriedades podem ser alteradas mantendo o mesmo objeto. Essa diferença é fundamental para entender atribuições e manipulação de dados em JavaScript.',example:"Exemplo: ao fazer let x = 10 e depois x = 20, você troca o valor da variável; o número 10 não foi alterado.",due:today(),interval:0},
 {id:14,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Strings são mutáveis ou imutáveis?',answer:'Imutáveis. Uma string existente não pode ser alterada.',explanation:'Strings são valores primitivos e, portanto, são imutáveis. Métodos podem produzir uma nova string, mas não alteram os caracteres da string original. Por exemplo, transformar um texto em maiúsculas resulta em outro valor. A variável pode então receber esse novo valor, dando a impressão de alteração, mas a string original em si não foi modificada.',example:"Exemplo: “ana”.toUpperCase() produz “ANA”; a string original “ana” continua sendo outro valor.",due:today(),interval:0},
 {id:15,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que é um objeto em JavaScript?',answer:'Uma coleção de propriedades, cada uma com nome e valor.',explanation:'Um objeto é uma coleção de propriedades. Cada propriedade possui um nome e um valor, permitindo reunir informações relacionadas numa única estrutura. O valor de uma propriedade pode ser de diferentes tipos, inclusive outro objeto. Diferentemente dos valores primitivos, objetos são mutáveis: suas propriedades podem ser adicionadas, removidas ou alteradas sem criar necessariamente um novo objeto.',example:"Exemplo: { nome: “Ana”, idade: 44 } reúne duas propriedades dentro do mesmo objeto.",due:today(),interval:0},
 {id:16,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Objetos são mutáveis. O que isso significa?',answer:'Suas propriedades podem ser alteradas.',explanation:'Dizer que objetos são mutáveis significa que seu conteúdo pode mudar depois que o objeto foi criado. É possível alterar o valor de uma propriedade, adicionar uma nova ou remover uma existente. O objeto continua sendo a mesma estrutura de referência. Essa característica diferencia objetos dos valores primitivos, cujo próprio conteúdo não pode ser alterado.',example:"Exemplo: em usuario.idade = 45, a propriedade muda sem precisar criar outro objeto.",due:today(),interval:0},
 {id:17,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que é um array em JavaScript?',answer:'Um objeto que representa uma coleção ordenada de valores.',explanation:'Um array é um tipo de objeto usado para representar uma coleção ordenada de valores. Cada elemento ocupa uma posição identificada por um índice, normalmente começando em zero. Arrays podem guardar valores de diferentes tipos e seu conteúdo pode ser alterado. Por serem objetos, também possuem propriedades e métodos usados para trabalhar com suas coleções.',example:"Exemplo: ['Angular', 'React'] é um array; Angular está no índice 0 e React no índice 1.",due:today(),interval:0},
 {id:18,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'O que são métodos em JavaScript?',answer:'Funções associadas a valores ou objetos.',explanation:'Métodos são funções associadas a valores ou objetos e são chamadas por meio deles. Eles permitem executar operações relacionadas àquele valor, como manipular uma string ou trabalhar com elementos de um array. Embora valores primitivos não sejam objetos, JavaScript permite acessar diversos métodos neles por mecanismos internos da linguagem. null e undefined são exceções importantes.',example:"Exemplo: 'ana'.toUpperCase() chama o método toUpperCase para produzir uma nova string.",due:today(),interval:0},
 {id:19,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Quais valores não permitem invocar métodos?',answer:'null e undefined.',explanation:'null e undefined são valores especiais que não permitem invocar métodos diretamente. undefined normalmente representa ausência de um valor atribuído, enquanto null é usado para representar intencionalmente ausência de valor. Tentar acessar uma propriedade ou chamar um método diretamente nesses valores causa erro. Por isso, é comum verificar se um valor existe antes de utilizá-lo.',example:"Exemplo: tentar executar null.toString() ou undefined.toString() gera erro.",due:today(),interval:0},
 {id:20,subject:'JavaScript',topic:'3.1 — Visão geral e definições',question:'Qual é a diferença entre const, let e var?',answer:'const declara constantes; let e var declaram variáveis.',explanation:'const é usado quando a variável não deve receber uma nova atribuição; let permite reatribuição e possui escopo de bloco. var é uma forma mais antiga de declarar variáveis e possui regras de escopo diferentes. Importante: const não torna um objeto imutável. Um objeto declarado com const ainda pode ter suas propriedades alteradas; o que não pode mudar é a referência atribuída à variável.',example:"Exemplo: let contador = 1 pode virar 2; const usuario não pode receber outro objeto, mas usuario.nome pode mudar.",due:today(),interval:0},

 {id:21,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões de projeto?',answer:'Soluções típicas e reutilizáveis para problemas comuns de projeto de software.',explanation:'Padrões de projeto são modelos de solução para problemas recorrentes no design de software. Eles não são códigos prontos que devem ser copiados, mas estruturas gerais que podem ser adaptadas ao contexto da aplicação. Funcionam como uma planta: mostram uma forma conhecida de organizar classes e objetos para resolver determinado problema de projeto.',example:"Exemplo: o padrão Observer resolve de forma reutilizável o problema de avisar vários objetos quando um estado muda.",due:today(),interval:0},
 {id:22,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'Como os padrões de projeto podem ser classificados?',answer:'Por complexidade, nível de detalhes, escala de aplicação e propósito.',explanation:'Os padrões variam desde soluções pequenas, ligadas a detalhes de uma linguagem, até decisões que influenciam a arquitetura de uma aplicação inteira. Além dessa escala, eles também podem ser classificados pela intenção do problema que resolvem. Nessa classificação por propósito, os grupos principais são criacionais, estruturais e comportamentais.',example:"Exemplo: um padrão de criação atua em uma parte do código; um padrão arquitetônico pode organizar a aplicação inteira.",due:today(),interval:0},
 {id:23,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões idiomáticos?',answer:'Padrões básicos e de baixo nível, geralmente específicos de uma linguagem.',explanation:'Padrões idiomáticos ficam mais próximos dos detalhes de implementação. Eles normalmente exploram características próprias de uma linguagem de programação e, por isso, não são necessariamente transferíveis para outra linguagem. Sua escala de aplicação é menor do que a dos padrões arquitetônicos.',example:"Exemplo: um idiom em JavaScript pode explorar recursos específicos da linguagem, como closures, para organizar uma solução.",due:today(),interval:0},
 {id:24,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'O que são padrões arquitetônicos?',answer:'Padrões de alto nível usados para projetar a arquitetura de uma aplicação.',explanation:'Padrões arquitetônicos trabalham em uma escala maior e podem orientar a organização de uma aplicação inteira. Por serem mais universais, podem ser implementados em diferentes linguagens. Eles tratam da estrutura geral do sistema, enquanto padrões de menor nível normalmente resolvem problemas mais localizados.',example:"Exemplo: MVC ou arquitetura em camadas orientam a estrutura geral do sistema, não apenas uma classe isolada.",due:today(),interval:0},
 {id:25,subject:'Padrões de Projeto',topic:'Classificação dos padrões',question:'Quais são os três grupos de padrões por propósito?',answer:'Criacionais, estruturais e comportamentais.',explanation:'Quando classificados pela intenção, os padrões são divididos em três grandes grupos. Os criacionais tratam da criação de objetos. Os estruturais tratam da composição de classes e objetos em estruturas maiores. Os comportamentais tratam da comunicação e da distribuição de responsabilidades entre objetos.',example:"Exemplo: Factory é criacional, Adapter é estrutural e Observer é comportamental.",due:today(),interval:0},
 {id:26,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que são padrões criacionais?',answer:'Mecanismos de criação de objetos que aumentam flexibilidade e reutilização.',explanation:'Padrões criacionais organizam a maneira como objetos são criados. A ideia é reduzir o acoplamento entre o código que precisa de um objeto e os detalhes de sua construção. Isso torna o sistema mais flexível quando a forma de criação muda e facilita reutilizar soluções de construção em diferentes partes da aplicação.',example:"Exemplo: uma Factory pode decidir qual classe de pagamento criar sem expor essa decisão ao código que vai usá-la.",due:today(),interval:0},
 {id:27,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'Quais são os padrões criacionais?',answer:'Factory Method, Abstract Factory, Builder, Prototype e Singleton.',explanation:'Os padrões criacionais são padrões relacionados à criação de objetos. Eles ajudam a tornar a criação mais flexível e reduzem o acoplamento entre o código que utiliza o objeto e a forma como ele é criado.',example:"Exemplo: Factory escolhe o objeto a criar; Builder monta um objeto complexo passo a passo; Singleton mantém uma única instância.",due:today(),interval:0},
 {id:28,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que são padrões estruturais?',answer:'Formas de compor classes e objetos em estruturas maiores, flexíveis e eficientes.',explanation:'Padrões estruturais tratam de como classes e objetos podem ser conectados para formar estruturas maiores sem perder flexibilidade. Eles ajudam a organizar relações entre componentes, adaptar interfaces e adicionar responsabilidades sem tornar a estrutura desnecessariamente rígida.',example:"Exemplo: um Adapter pode fazer uma API antiga funcionar com a interface esperada pelo código novo.",due:today(),interval:0},
 {id:29,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'Quais são os padrões estruturais?',answer:'Adapter, Bridge, Composite, Decorator, Facade, Flyweight e Proxy.',explanation:'O grupo estrutural contém sete padrões clássicos: Adapter, Bridge, Composite, Decorator, Facade, Flyweight e Proxy. Apesar de resolverem problemas diferentes, todos se concentram em como classes e objetos são combinados e organizados para formar estruturas maiores.',example:"Exemplo: uma Facade oferece uma entrada simples para um conjunto complexo de serviços internos.",due:today(),interval:0},
 {id:30,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que são padrões comportamentais?',answer:'Padrões para comunicação eficiente e distribuição de responsabilidades entre objetos.',explanation:'Padrões comportamentais se concentram na interação entre objetos. Eles ajudam a definir quem executa determinada responsabilidade, como uma solicitação percorre o sistema e como diferentes objetos colaboram sem ficarem excessivamente acoplados uns aos outros.',example:"Exemplo: no Observer, vários componentes podem ser avisados automaticamente quando um dado observado muda.",due:today(),interval:0},
 {id:31,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'Quais são os padrões comportamentais?',answer:'Chain of Responsibility, Command, Iterator, Mediator, Memento, Observer, State, Strategy, Template Method e Visitor.',explanation:'O catálogo apresenta dez padrões comportamentais: Chain of Responsibility, Command, Iterator, Mediator, Memento, Observer, State, Strategy, Template Method e Visitor. Eles tratam principalmente de comunicação, fluxo de responsabilidades e colaboração entre objetos.',example:"Exemplo: Strategy troca um algoritmo em runtime, Observer notifica interessados e Command encapsula uma ação.",due:today(),interval:0},
 {id:76,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que é o Factory Method?',answer:'Um padrão que delega a criação de objetos para subclasses ou métodos especializados.',explanation:'Factory Method define uma forma de criar objetos sem acoplar o código cliente a uma classe concreta. A criação fica encapsulada em um método que pode ser sobrescrito ou especializado.',example:"Exemplo: um sistema de notificações pode criar EmailNotification ou SmsNotification sem o cliente instanciar essas classes diretamente.",due:today(),interval:0},
 {id:77,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que é o Abstract Factory?',answer:'Um padrão para criar famílias de objetos relacionados sem expor classes concretas.',explanation:'Abstract Factory fornece uma interface para criar vários objetos que pertencem à mesma família. O cliente usa a fábrica abstrata e não precisa conhecer as implementações concretas.',example:"Exemplo: uma fábrica de UI pode criar Button e Checkbox para tema claro ou tema escuro.",due:today(),interval:0},
 {id:78,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que é o Builder?',answer:'Um padrão que constrói objetos complexos passo a passo.',explanation:'Builder separa a construção de um objeto complexo da sua representação final. Assim, o mesmo processo de construção pode gerar diferentes configurações.',example:"Exemplo: montar uma requisição HTTP adicionando URL, headers, body e autenticação em etapas.",due:today(),interval:0},
 {id:79,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que é o Prototype?',answer:'Um padrão que cria novos objetos copiando uma instância existente.',explanation:'Prototype usa clonagem para criar objetos a partir de um modelo já configurado. É útil quando criar um objeto do zero é caro ou trabalhoso.',example:"Exemplo: duplicar uma configuração padrão de dashboard e alterar apenas alguns campos.",due:today(),interval:0},
 {id:80,subject:'Padrões de Projeto',topic:'Padrões criacionais',question:'O que é o Singleton?',answer:'Um padrão que garante uma única instância de uma classe e acesso global a ela.',explanation:'Singleton controla a criação para que apenas uma instância exista durante a execução. Deve ser usado com cuidado porque pode introduzir estado global e acoplamento.',example:"Exemplo: um serviço central de configuração pode manter uma única instância compartilhada.",due:today(),interval:0},

 {id:81,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Adapter?',answer:'Um padrão que converte uma interface em outra esperada pelo cliente.',explanation:'Adapter permite que componentes incompatíveis trabalhem juntos. Ele envolve um objeto existente e traduz chamadas para a interface esperada.',example:"Exemplo: adaptar a resposta de uma API antiga para o formato usado pela aplicação nova.",due:today(),interval:0},
 {id:82,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Bridge?',answer:'Um padrão que separa abstração e implementação para que evoluam independentemente.',explanation:'Bridge evita uma explosão de subclasses ao dividir duas dimensões que variam separadamente. A abstração passa a trabalhar com uma implementação por composição.',example:"Exemplo: diferentes controles remotos podem funcionar com diferentes marcas de TV sem criar uma classe para cada combinação.",due:today(),interval:0},
 {id:83,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Composite?',answer:'Um padrão que trata objetos individuais e grupos de objetos de forma uniforme.',explanation:'Composite organiza objetos em uma estrutura de árvore. O cliente pode executar a mesma operação em um item simples ou em um conjunto de itens.',example:"Exemplo: arquivos e pastas podem implementar a mesma operação de calcular tamanho.",due:today(),interval:0},
 {id:84,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Decorator?',answer:'Um padrão que adiciona comportamento a um objeto sem alterar sua classe.',explanation:'Decorator envolve um objeto com outros objetos que acrescentam responsabilidades dinamicamente. É uma alternativa flexível à herança para combinar comportamentos.',example:"Exemplo: adicionar cache, log e autenticação ao redor de um serviço sem modificar o serviço original.",due:today(),interval:0},
 {id:85,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Facade?',answer:'Um padrão que oferece uma interface simples para um conjunto complexo de componentes.',explanation:'Facade cria um ponto de entrada mais simples para um subsistema. Ela reduz a quantidade de detalhes internos que o cliente precisa conhecer.',example:"Exemplo: checkout() pode coordenar pagamento, estoque e entrega por trás de uma única chamada.",due:today(),interval:0},
 {id:86,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Flyweight?',answer:'Um padrão que compartilha estado comum para economizar memória.',explanation:'Flyweight reduz o custo de criar muitos objetos semelhantes. Parte do estado é compartilhada entre instâncias, enquanto apenas o estado variável permanece separado.',example:"Exemplo: milhares de caracteres em um editor podem compartilhar dados de fonte e estilo.",due:today(),interval:0},
 {id:87,subject:'Padrões de Projeto',topic:'Padrões estruturais',question:'O que é o Proxy?',answer:'Um padrão que controla o acesso a outro objeto por meio de um intermediário.',explanation:'Proxy mantém a mesma interface do objeto real, mas adiciona uma camada de controle. Essa camada pode cuidar de cache, segurança, lazy loading ou acesso remoto.',example:"Exemplo: um proxy pode buscar dados da API somente na primeira vez e depois retornar o valor em cache.",due:today(),interval:0},

 {id:88,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é Chain of Responsibility?',answer:'Um padrão que passa uma solicitação por uma cadeia de possíveis manipuladores.',explanation:'Cada objeto da cadeia decide se trata a solicitação ou se a encaminha para o próximo. Isso reduz o acoplamento entre quem envia e quem processa.',example:"Exemplo: uma requisição pode passar por autenticação, autorização e validação antes de chegar ao handler final.",due:today(),interval:0},
 {id:89,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Command?',answer:'Um padrão que encapsula uma ação ou solicitação como um objeto.',explanation:'Command transforma uma operação em um objeto independente. Isso facilita filas, histórico, desfazer ações e desacoplamento entre quem pede e quem executa.',example:"Exemplo: ações de editor como Copiar, Colar e Desfazer podem ser representadas por comandos.",due:today(),interval:0},
 {id:90,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Iterator?',answer:'Um padrão que percorre elementos de uma coleção sem expor sua estrutura interna.',explanation:'Iterator fornece uma forma padronizada de acessar elementos sequencialmente. O cliente não precisa saber como a coleção armazena seus dados internamente.',example:"Exemplo: percorrer uma lista ou árvore usando a mesma ideia de next() sem conhecer a estrutura interna.",due:today(),interval:0},
 {id:91,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Mediator?',answer:'Um padrão que centraliza a comunicação entre objetos em um mediador.',explanation:'Mediator reduz dependências diretas entre vários componentes. Em vez de cada objeto conhecer todos os outros, eles conversam por meio de um objeto central.',example:"Exemplo: em um formulário, um mediador pode coordenar campo, botão e validação sem eles se referenciarem diretamente.",due:today(),interval:0},
 {id:92,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Memento?',answer:'Um padrão que salva e restaura o estado de um objeto sem expor sua implementação.',explanation:'Memento captura um snapshot do estado interno para permitir restauração futura. É comum em funcionalidades de desfazer ou histórico.',example:"Exemplo: um editor salva versões anteriores do documento para permitir voltar a um estado anterior.",due:today(),interval:0},
 {id:93,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Observer?',answer:'Um padrão que notifica vários interessados quando um objeto muda de estado.',explanation:'Observer estabelece uma relação de assinatura. O objeto observado publica mudanças e os observadores inscritos são notificados automaticamente.',example:"Exemplo: vários componentes da tela podem reagir quando um estado compartilhado é atualizado.",due:today(),interval:0},
 {id:94,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o State?',answer:'Um padrão que altera o comportamento de um objeto conforme seu estado interno.',explanation:'State move comportamentos dependentes de estado para objetos específicos. Assim, o objeto principal muda de comportamento trocando seu estado atual.',example:"Exemplo: um pedido pode se comportar de forma diferente quando está Novo, Pago, Enviado ou Cancelado.",due:today(),interval:0},
 {id:95,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Strategy?',answer:'Um padrão que permite trocar algoritmos ou comportamentos de forma intercambiável.',explanation:'Strategy encapsula diferentes algoritmos atrás de uma mesma interface. O cliente pode escolher qual estratégia usar sem mudar sua própria lógica.',example:"Exemplo: um checkout pode trocar entre cálculo de frete normal, expresso ou retirada em loja.",due:today(),interval:0},
 {id:96,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Template Method?',answer:'Um padrão que define a estrutura de um algoritmo e permite variar algumas etapas.',explanation:'Template Method estabelece um esqueleto de execução em uma classe base. Subclasses podem personalizar etapas específicas sem alterar a sequência geral.',example:"Exemplo: importar arquivos pode seguir abrir, ler, validar e salvar, variando apenas a leitura de CSV ou JSON.",due:today(),interval:0},
 {id:97,subject:'Padrões de Projeto',topic:'Padrões comportamentais',question:'O que é o Visitor?',answer:'Um padrão que adiciona operações a uma estrutura de objetos sem alterar suas classes.',explanation:'Visitor separa operações da estrutura de objetos sobre a qual elas atuam. É útil quando a estrutura muda pouco, mas novas operações são adicionadas com frequência.',example:"Exemplo: uma árvore de documentos pode receber visitantes diferentes para exportar PDF, gerar HTML ou calcular estatísticas.",due:today(),interval:0},
 {id:32,subject:'Angular',topic:'Angular',question:'O que são diretivas no Angular e para que servem?',answer:'Classes que adicionam ou modificam comportamento ou estrutura no DOM.',explanation:'Diretivas permitem estender o HTML. Componentes são diretivas com template; diretivas de atributo alteram aparência ou comportamento; diretivas estruturais controlam a estrutura renderizada.',example:'Exemplo: uma diretiva pode destacar um campo inválido ou controlar se um bloco aparece na tela.',due:today(),interval:0},
 {id:33,subject:'Angular',topic:'Angular',question:'Quais são os tipos de diretivas no Angular?',answer:'Componentes, diretivas de atributo e diretivas estruturais.',explanation:'Componentes possuem template. Diretivas de atributo alteram comportamento ou aparência de elementos. Diretivas estruturais alteram a estrutura da view adicionando ou removendo conteúdo.',example:'Exemplo: um componente renderiza uma tela; ngClass altera classes; *ngIf, na sintaxe tradicional, controla a existência de um bloco.',due:today(),interval:0},
 {id:34,subject:'Angular',topic:'Performance',question:'O que analisar se o Front-end está lento e o Backend não é a causa?',answer:'Renderizações, change detection, bundle, DOM, imagens, chamadas e vazamentos de memória.',explanation:'O diagnóstico deve separar custo de carregamento, renderização e execução. DevTools e profiler ajudam a localizar bundles grandes, tarefas longas, renderizações excessivas e recursos pesados.',example:'Exemplo: se a API responde rápido mas a lista trava ao renderizar milhares de itens, o gargalo está no Front-end.',due:today(),interval:0},
 {id:35,subject:'Angular',topic:'Performance',question:'Como melhorar uma tela com muitas imagens ou elementos visuais?',answer:'Lazy loading, otimização de imagens, @defer, virtualização e carregamento sob demanda.',explanation:'A ideia é reduzir o que precisa ser baixado e renderizado inicialmente. Imagens podem ser comprimidas e carregadas sob demanda; conteúdo pesado pode ser adiado; listas extensas podem ser virtualizadas.',example:'Exemplo: uma galeria pode carregar apenas as imagens próximas da área visível e adiar o restante.',due:today(),interval:0},
 {id:36,subject:'Angular',topic:'Angular',question:'Quais são as principais tecnologias do ecossistema Angular?',answer:'Angular usa TypeScript e RxJS; Router, Forms e ferramentas de teste complementam o ecossistema.',explanation:'Angular é um framework baseado em TypeScript e integra recursos para componentes, DI, roteamento, formulários e programação reativa com RxJS. Ferramentas de teste variam por projeto.',example:'Exemplo: um formulário Angular pode usar Reactive Forms e RxJS enquanto o Router controla a navegação.',due:today(),interval:0},
 {id:37,subject:'Angular',topic:'Arquitetura',question:'O que é Server Driven UI (SDUI) e como funciona?',answer:'O servidor envia uma configuração da interface e o Front-end interpreta e renderiza os componentes.',explanation:'Em SDUI, parte da decisão sobre o que exibir vem de uma estrutura de dados entregue pelo servidor. O cliente possui componentes conhecidos e mapeia a configuração recebida para esses componentes.',example:'Exemplo: a API envia que a tela contém título, banner e botão; o Front-end associa cada tipo ao componente correspondente.',due:today(),interval:0},
 {id:38,subject:'Angular',topic:'Angular',question:'Qual é uma diferença central entre Angular e React?',answer:'Angular é um framework completo; React é uma biblioteca focada na construção de interfaces.',explanation:'Angular oferece de forma integrada recursos como DI, Router e Forms. React concentra-se na camada de UI e normalmente combina outras bibliotecas conforme a arquitetura escolhida.',example:'Exemplo: no Angular, roteamento e DI fazem parte do ecossistema oficial; em React, a composição do stack tende a ser mais flexível.',due:today(),interval:0},
 {id:39,subject:'Angular',topic:'Angular',question:'Quais arquivos normalmente compõem um componente Angular?',answer:'TypeScript, template HTML, estilos CSS/SCSS e, quando aplicável, arquivo de teste.',explanation:'O arquivo .ts contém a classe e metadados; o HTML define o template; CSS ou SCSS cuida dos estilos; o spec contém testes. Templates e estilos também podem ser inline.',example:'Exemplo: usuario.component.ts, usuario.component.html, usuario.component.scss e usuario.component.spec.ts.',due:today(),interval:0},
 {id:40,subject:'Angular',topic:'Angular',question:'Qual é a responsabilidade de um Service no Angular?',answer:'Encapsular lógica reutilizável e responsabilidades que não pertencem à apresentação.',explanation:'Services ajudam a separar responsabilidades dos componentes e podem ser compartilhados por injeção de dependência. São comuns para acesso a dados, estado e regras reutilizáveis.',example:'Exemplo: ProdutoService consulta a API e entrega os produtos ao componente que apenas os apresenta.',due:today(),interval:0},
 {id:41,subject:'Angular',topic:'Angular',question:'Que tipos de lógica normalmente ficam em um Service?',answer:'Chamadas HTTP, acesso a dados, estado compartilhado, transformações e regras reutilizáveis.',explanation:'A lógica que não é responsabilidade direta da view pode ser extraída para services. Isso reduz acoplamento e facilita reutilização e testes.',example:'Exemplo: um service pode buscar pedidos, transformar a resposta e disponibilizar os dados para diferentes componentes.',due:today(),interval:0},
 {id:42,subject:'Angular',topic:'Angular',question:'O que são NgModules e para que servem?',answer:'Estruturas que agrupam e configuram partes de aplicações Angular baseadas em módulos.',explanation:'NgModules organizam declarações, imports e providers em aplicações que usam a arquitetura baseada em módulos. Com standalone, muitas dessas necessidades podem ser atendidas sem NgModules.',example:'Exemplo: uma feature legada pode ter um PedidosModule reunindo componentes e dependências daquela área.',due:today(),interval:0},
 {id:43,subject:'Angular',topic:'Angular',question:'Por que uma aplicação Angular pode ser organizada em módulos?',answer:'Para agrupar funcionalidades relacionadas, organizar dependências e separar features.',explanation:'Em arquiteturas baseadas em NgModules, módulos ajudam a criar limites entre funcionalidades e podem participar do lazy loading. Angular moderno também permite organização por features usando standalone.',example:'Exemplo: uma área administrativa pode ser isolada em uma feature carregada apenas quando acessada.',due:today(),interval:0},
 {id:44,subject:'Angular',topic:'Angular',question:'Por que não concentrar toda a lógica nos componentes?',answer:'Para separar responsabilidades, reduzir acoplamento e facilitar manutenção, reutilização e testes.',explanation:'Componentes devem se concentrar principalmente na apresentação e interação da view. Regras e acesso a dados podem ser distribuídos em abstrações apropriadas.',example:'Exemplo: o componente exibe clientes enquanto um service cuida da consulta e transformação dos dados.',due:today(),interval:0},
 {id:45,subject:'Angular',topic:'Angular',question:'O que são Standalone Components?',answer:'Componentes que podem importar dependências diretamente sem serem declarados em um NgModule.',explanation:'Com standalone: true, componentes podem compor suas dependências diretamente. A abordagem reduz a necessidade de módulos para organizar e inicializar aplicações.',example:'Exemplo: um componente standalone pode importar CommonModule ou outros componentes diretamente em imports.',due:today(),interval:0},
 {id:46,subject:'Angular',topic:'Angular',question:'Como criar uma aplicação Angular sem depender de NgModules?',answer:'Usando APIs standalone para componentes, diretivas, pipes, rotas e bootstrap.',explanation:'Aplicações modernas podem iniciar com bootstrapApplication e compor features com elementos standalone, sem um AppModule central.',example:'Exemplo: bootstrapApplication(AppComponent) inicia uma aplicação cujo componente raiz é standalone.',due:today(),interval:0},
 {id:47,subject:'Angular',topic:'Performance',question:'O que é Lazy Loading?',answer:'É o carregamento de código ou recursos somente quando eles são necessários.',explanation:'Lazy loading reduz o trabalho inicial da aplicação ao adiar partes que o usuário ainda não precisa. Isso pode diminuir o bundle inicial e melhorar o tempo de carregamento.',example:'Exemplo: o código da área de relatórios só é baixado quando o usuário acessa essa rota.',due:today(),interval:0},
 {id:48,subject:'Angular',topic:'Performance',question:'Por que utilizar Lazy Loading em uma aplicação Angular?',answer:'Para reduzir o carregamento inicial, baixando features apenas quando forem necessárias.',explanation:'Separar funcionalidades em chunks evita enviar todo o código logo na primeira abertura. O benefício é maior em aplicações grandes com áreas acessadas em momentos diferentes.',example:'Exemplo: a área administrativa não precisa fazer parte do bundle inicial de um usuário que ainda está no login.',due:today(),interval:0},
 {id:49,subject:'Angular',topic:'Performance',question:'Como o Lazy Loading funciona no Angular?',answer:'O Router usa imports dinâmicos, como loadComponent ou loadChildren, para carregar código sob demanda.',explanation:'A configuração de rotas pode apontar para funções que importam componentes ou conjuntos de rotas apenas quando o caminho correspondente é acessado.',example:'Exemplo: loadComponent pode importar o componente de Perfil somente quando a rota /perfil for aberta.',due:today(),interval:0},
 {id:50,subject:'Angular',topic:'Rotas',question:'O que é o Angular Router e para que serve?',answer:'É o mecanismo de navegação que relaciona URLs às views da aplicação.',explanation:'O Router interpreta a URL, encontra a configuração correspondente e controla a navegação client-side. Também suporta parâmetros, guards, resolvers e rotas filhas.',example:'Exemplo: /clientes/42 pode abrir o componente de detalhes e disponibilizar o id 42 como parâmetro.',due:today(),interval:0},
 {id:51,subject:'Angular',topic:'Rotas',question:'Como as rotas são configuradas no Angular?',answer:'Por uma configuração de Routes que associa paths a componentes, redirects ou carregamento lazy.',explanation:'Cada objeto de rota descreve como um caminho deve ser tratado. A configuração pode incluir children, guards, parâmetros e carregamento sob demanda.',example:'Exemplo: { path: \'perfil\', component: PerfilComponent } associa /perfil ao componente.',due:today(),interval:0},
 {id:52,subject:'Angular',topic:'Rotas',question:'Como o Router navega sem recarregar toda a página?',answer:'Atualiza a URL e troca a view renderizada no RouterOutlet por navegação client-side.',explanation:'Em uma SPA, o navegador não precisa solicitar um novo documento HTML a cada rota. O Angular intercepta a navegação, resolve a rota e atualiza a parte correspondente da interface.',example:'Exemplo: routerLink=\'/perfil\' muda a rota e o conteúdo exibido sem um reload completo da página.',due:today(),interval:0},
 {id:53,subject:'Angular',topic:'RxJS',question:'O que é um Observable?',answer:'Um fluxo que pode emitir zero, um ou vários valores ao longo do tempo.',explanation:'Observables representam sequências de valores e podem ser compostos com operadores. Em Angular aparecem em HTTP, formulários, Router e diversos fluxos assíncronos.',example:'Exemplo: valueChanges de um formulário emite um novo valor sempre que o campo é alterado.',due:today(),interval:0},
 {id:54,subject:'Angular',topic:'RxJS',question:'Qual é a diferença entre Observable e Promise?',answer:'Promise resolve uma vez; Observable pode emitir vários valores e permite composição e cancelamento por subscription.',explanation:'Promises representam um resultado assíncrono único. Observables representam streams e possuem operadores para transformar, combinar e controlar emissões.',example:'Exemplo: uma Promise pode carregar uma configuração uma vez; um Observable pode acompanhar continuamente alterações de um formulário.',due:today(),interval:0},
 {id:55,subject:'Angular',topic:'RxJS',question:'Para que servem os operadores do RxJS?',answer:'Para transformar, filtrar, combinar e controlar fluxos de Observables.',explanation:'Operadores permitem criar pipelines declarativos. Cada operador recebe um fluxo e produz um comportamento ou fluxo resultante sem exigir lógica imperativa espalhada nas subscriptions.',example:'Exemplo: filter descarta valores indesejados e map transforma os valores que continuam no fluxo.',due:today(),interval:0},
 {id:56,subject:'Angular',topic:'RxJS',question:'Para que serve o operador map?',answer:'Para transformar cada valor emitido e produzir um novo valor.',explanation:'map realiza uma transformação síncrona de cada emissão. Ele não é o operador adequado para achatar um Observable retornado pela transformação.',example:'Exemplo: of(1,2,3).pipe(map(n => n * 2)) emite 2, 4 e 6.',due:today(),interval:0},
 {id:57,subject:'Angular',topic:'RxJS',question:'Para que serve o operador filter?',answer:'Para permitir apenas as emissões que atendem a uma condição.',explanation:'filter avalia cada valor emitido. Se o predicado retornar true, o valor continua no fluxo; caso contrário, é ignorado.',example:'Exemplo: filter(n => n > 10) deixa passar apenas números maiores que 10.',due:today(),interval:0},
 {id:58,subject:'Angular',topic:'RxJS',question:'Para que serve o operador switchMap?',answer:'Para trocar para um novo Observable e cancelar a subscription interna anterior.',explanation:'switchMap é útil quando somente o resultado mais recente interessa. A cada nova emissão da origem, a subscription interna anterior é encerrada e uma nova começa.',example:'Exemplo: em uma busca digitada, uma nova pesquisa substitui a requisição anterior.',due:today(),interval:0},
 {id:59,subject:'Angular',topic:'RxJS',question:'Para que serve o operador mergeMap?',answer:'Para projetar valores em Observables internos e processá-los concorrentemente.',explanation:'mergeMap mantém múltiplas subscriptions internas ativas ao mesmo tempo. A ordem das respostas não é garantida, por isso é útil quando as operações podem ocorrer em paralelo.',example:'Exemplo: salvar vários itens independententes em paralelo, sem precisar esperar um terminar para iniciar outro.',due:today(),interval:0},
 {id:60,subject:'Angular',topic:'RxJS',question:'Para que serve o operador concatMap?',answer:'Para executar Observables internos em sequência, preservando a ordem.',explanation:'concatMap aguarda o Observable interno atual terminar antes de iniciar o próximo. É adequado quando a ordem das operações importa.',example:'Exemplo: enviar alterações ao servidor uma por vez na mesma ordem em que foram geradas.',due:today(),interval:0},
 {id:61,subject:'Angular',topic:'RxJS',question:'Para que serve o operador exhaustMap?',answer:'Para ignorar novas emissões enquanto o Observable interno atual ainda está em execução.',explanation:'exhaustMap evita iniciar uma nova operação até que a atual termine. Depois da conclusão, uma nova emissão poderá ser aceita.',example:'Exemplo: ignorar cliques repetidos no botão Entrar enquanto a requisição de login ainda está em andamento.',due:today(),interval:0},
 {id:62,subject:'Angular',topic:'RxJS',question:'Para que serve o operador tap?',answer:'Para executar efeitos colaterais sem transformar os valores do fluxo.',explanation:'tap observa as emissões e permite executar ações auxiliares, mantendo o valor que segue pelo pipeline. Não deve ser usado como substituto de map para transformação.',example:'Exemplo: tap(value => console.log(value)) registra o valor e o fluxo continua com o mesmo value.',due:today(),interval:0},
 {id:63,subject:'Angular',topic:'RxJS',question:'Para que serve o operador catchError?',answer:'Para interceptar erros de um Observable e definir como o fluxo deve reagir.',explanation:'catchError recebe o erro e pode retornar outro Observable, permitindo fornecer fallback, transformar o erro ou decidir como continuar.',example:'Exemplo: uma falha HTTP pode ser convertida em of([]) quando uma lista vazia é um fallback apropriado.',due:today(),interval:0},
 {id:64,subject:'Angular',topic:'RxJS',question:'Para que serve o operador take?',answer:'Para receber uma quantidade definida de emissões e então completar a subscription.',explanation:'take(n) permite que apenas as primeiras n emissões passem. Ao atingir a quantidade, o fluxo resultante completa automaticamente.',example:'Exemplo: take(1) recebe apenas a primeira emissão de um Observable.',due:today(),interval:0},
 {id:65,subject:'Angular',topic:'RxJS',question:'Para que serve o operador takeUntil?',answer:'Para manter a subscription ativa até que outro Observable emita um valor.',explanation:'takeUntil usa um Observable notificador como sinal de encerramento. É útil para controlar o ciclo de vida de subscriptions.',example:'Exemplo: quando destroy$ emite, os fluxos configurados com takeUntil(destroy$) são encerrados.',due:today(),interval:0},
 {id:66,subject:'Angular',topic:'RxJS',question:'Para que serve o operador debounceTime?',answer:'Para esperar um período sem novas emissões antes de liberar o valor mais recente.',explanation:'debounceTime reduz eventos muito frequentes. Cada nova emissão reinicia a espera; somente após o intervalo de silêncio o valor é emitido.',example:'Exemplo: em uma busca, debounceTime(300) evita chamar a API a cada tecla digitada rapidamente.',due:today(),interval:0},
 {id:67,subject:'Angular',topic:'RxJS',question:'Para que serve o operador distinctUntilChanged?',answer:'Para evitar emissões consecutivas consideradas iguais.',explanation:'distinctUntilChanged compara a emissão atual com a anterior e bloqueia repetições consecutivas segundo a comparação utilizada.',example:'Exemplo: se uma busca emitir \'angular\' duas vezes seguidas, a segunda pode ser ignorada.',due:today(),interval:0},
 {id:68,subject:'Angular',topic:'RxJS',question:'Qual a diferença entre switchMap, mergeMap, concatMap e exhaustMap?',answer:'switchMap troca, mergeMap concorre, concatMap enfileira e exhaustMap ignora novas emissões enquanto executa.',explanation:'Os quatro transformam valores em Observables internos, mas diferem no tratamento da concorrência. A escolha depende de cancelar, paralelizar, ordenar ou bloquear novas operações.',example:'Exemplo: busca usa switchMap; tarefas paralelas podem usar mergeMap; fila usa concatMap; prevenção de clique duplo pode usar exhaustMap.',due:today(),interval:0},
 {id:69,subject:'Angular',topic:'Ciclo de vida',question:'O que é o ciclo de vida de um componente Angular?',answer:'É a sequência de criação, atualização, renderização e destruição de um componente.',explanation:'Angular gerencia um componente desde sua instanciação até sua remoção. Lifecycle hooks permitem executar lógica em momentos específicos desse processo.',example:'Exemplo: um componente pode inicializar dados ao nascer e liberar recursos quando sai da tela.',due:today(),interval:0},
 {id:70,subject:'Angular',topic:'Ciclo de vida',question:'Quais são os principais Lifecycle Hooks do Angular?',answer:'ngOnChanges, ngOnInit, ngDoCheck, ngAfterContentInit/Checked, ngAfterViewInit/Checked e ngOnDestroy.',explanation:'Cada hook corresponde a um momento específico do ciclo de vida. Saber a finalidade de cada um é mais importante do que apenas memorizar a lista.',example:'Exemplo: ngOnInit inicializa; ngAfterViewInit atua após a view; ngOnDestroy é usado para cleanup.',due:today(),interval:0},
 {id:71,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngOnChanges?',answer:'Para reagir a alterações nos inputs do componente.',explanation:'ngOnChanges é chamado quando inputs vinculados recebem mudanças e fornece SimpleChanges com informações sobre os valores anterior e atual.',example:'Exemplo: ao receber outro id por @Input, o componente pode reagir à mudança e atualizar dados relacionados.',due:today(),interval:0},
 {id:72,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngOnInit?',answer:'Para executar inicializações após o Angular definir os inputs iniciais do componente.',explanation:'ngOnInit é executado uma vez na inicialização do componente. É adequado para lógica inicial que precisa ocorrer depois que os inputs iniciais foram definidos.',example:'Exemplo: iniciar a configuração de uma tela usando os dados iniciais recebidos pelo componente.',due:today(),interval:0},
 {id:73,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngDoCheck?',answer:'Para executar verificações personalizadas durante a detecção de mudanças.',explanation:'ngDoCheck permite implementar lógica de detecção que o mecanismo padrão não cobre diretamente. Como pode executar com frequência, deve ser usado com cuidado.',example:'Exemplo: detectar manualmente uma alteração específica em uma estrutura quando a estratégia padrão não atende ao caso.',due:today(),interval:0},
 {id:74,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngAfterContentInit?',answer:'Para executar lógica depois que o conteúdo projetado no componente é inicializado.',explanation:'Esse hook ocorre após Angular inicializar o conteúdo recebido por projeção, como elementos inseridos via ng-content.',example:'Exemplo: acessar uma referência obtida com ContentChild depois que o conteúdo projetado estiver disponível.',due:today(),interval:0},
 {id:75,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngAfterContentChecked?',answer:'Para reagir após a verificação do conteúdo projetado no componente.',explanation:'É executado depois que Angular verifica o conteúdo projetado. Pode ocorrer muitas vezes, então operações pesadas nesse hook prejudicam a performance.',example:'Exemplo: observar uma condição ligada ao conteúdo projetado após uma rodada de verificação.',due:today(),interval:0},
 {id:76,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngAfterViewInit?',answer:'Para executar lógica depois que a view e as views filhas são inicializadas.',explanation:'Nesse ponto, elementos e componentes consultados pela view já foram inicializados, tornando o hook útil para interações que dependem deles.',example:'Exemplo: acessar um elemento com ViewChild depois que a view foi criada.',due:today(),interval:0},
 {id:77,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngAfterViewChecked?',answer:'Para reagir depois que a view e as views filhas são verificadas.',explanation:'O hook roda após verificações da view e pode executar muitas vezes. Deve-se evitar lógica pesada ou alterações que provoquem ciclos de detecção desnecessários.',example:'Exemplo: uma verificação específica pode ocorrer após Angular conferir a view, desde que seja realmente necessária.',due:today(),interval:0},
 {id:78,subject:'Angular',topic:'Ciclo de vida',question:'Para que serve o ngOnDestroy?',answer:'Para liberar recursos que não devem continuar ativos depois que o componente for destruído.',explanation:'Destruir o componente não encerra necessariamente tudo que ele iniciou. Timers, listeners e algumas subscriptions podem sobreviver e precisam de cleanup apropriado.',example:'Exemplo: um setInterval iniciado pelo componente deve ser interrompido com clearInterval quando não for mais necessário.',due:today(),interval:0},
 {id:79,subject:'Angular',topic:'Ciclo de vida',question:'Em que ordem os principais Lifecycle Hooks são executados?',answer:'OnChanges → OnInit → DoCheck → AfterContentInit/Checked → AfterViewInit/Checked; OnDestroy ocorre ao destruir.',explanation:'Alguns hooks executam uma vez e outros se repetem durante verificações. ngOnDestroy pertence ao encerramento, não ao ciclo repetitivo de atualização.',example:'Exemplo: na criação, OnInit ocorre antes de AfterViewInit; ao remover o componente, OnDestroy é chamado.',due:today(),interval:0},
 {id:80,subject:'Angular',topic:'Ciclo de vida',question:'O que pode continuar ativo após um componente ser destruído?',answer:'Timers, listeners, subscriptions e outros recursos externos que não estejam vinculados automaticamente à vida do componente.',explanation:'A instância sair da tela não garante que recursos criados fora dela sejam encerrados. Se continuarem referenciando objetos, podem consumir processamento e memória.',example:'Exemplo: um setInterval pode continuar disparando mesmo depois de o componente ter sido removido.',due:today(),interval:0},
 {id:81,subject:'Angular',topic:'Ciclo de vida',question:'Quais recursos podem precisar ser liberados ao destruir um componente?',answer:'Subscriptions, timers, listeners e integrações ou referências que não devem sobreviver ao componente.',explanation:'O cleanup depende do recurso. Alguns mecanismos modernos do Angular fazem gerenciamento automático em determinados contextos, mas recursos manuais ainda precisam ser avaliados.',example:'Exemplo: remover um listener adicionado manualmente ao window quando o componente deixa de existir.',due:today(),interval:0},
 {id:82,subject:'Angular',topic:'Ciclo de vida',question:'Como a limpeza de recursos ajuda a evitar Memory Leaks?',answer:'Remove referências e processos desnecessários que poderiam manter objetos vivos na memória.',explanation:'O garbage collector só libera objetos que deixaram de ser alcançáveis. Listeners, timers ou subscriptions podem manter referências e impedir a liberação esperada.',example:'Exemplo: um listener global que referencia o componente pode mantê-lo alcançável mesmo depois de sair da tela.',due:today(),interval:0},
 {id:83,subject:'Angular',topic:'Testes',question:'Para que o Jest é utilizado em uma aplicação Angular?',answer:'Para executar testes e oferecer assertions, mocks e spies para validar unidades de código.',explanation:'Jest é um framework de testes usado para verificar comportamento de funções, services, componentes e outras unidades. A configuração depende do projeto.',example:'Exemplo: um teste pode mockar uma dependência de um service e verificar se um método foi chamado com os argumentos corretos.',due:today(),interval:0},
 {id:84,subject:'Angular',topic:'Testes',question:'O que é o padrão Arrange, Act, Assert (AAA)?',answer:'Uma estrutura de teste: preparar o cenário, executar a ação e verificar o resultado.',explanation:'AAA torna o teste legível ao separar claramente configuração, comportamento testado e expectativa. Não é exclusivo do Angular ou Jest.',example:'Exemplo: Arrange cria o usuário; Act chama salvar(); Assert verifica se o repositório recebeu os dados esperados.',due:today(),interval:0},
 {id:85,subject:'Angular',topic:'Testes',question:'O que é cobertura de testes?',answer:'É uma medida de quanto do código foi executado durante os testes.',explanation:'Ferramentas de coverage podem medir statements, branches, funções e linhas. Cobertura indica execução, não garante por si só a qualidade das assertions.',example:'Exemplo: uma linha pode estar coberta porque foi executada, mesmo que nenhum teste valide corretamente seu resultado.',due:today(),interval:0},
 {id:86,subject:'Angular',topic:'Testes',question:'O que significa ter 90% de cobertura de testes?',answer:'Significa que a métrica configurada reporta cerca de 90% de cobertura; não significa 90% dos comportamentos validados.',explanation:'É preciso saber qual dimensão está sendo medida: linhas, statements, branches ou funções. Um percentual alto não substitui bons cenários e assertions.',example:'Exemplo: 90% das linhas podem executar nos testes enquanto um branch crítico continua sem um cenário que valide seu comportamento.',due:today(),interval:0},
 {id:87,subject:'Angular',topic:'Testes',question:'Para que o Cypress é utilizado e como testa os fluxos da aplicação?',answer:'Para automatizar interações no navegador e validar fluxos integrados ou E2E da aplicação.',explanation:'Cypress pode navegar, clicar, preencher formulários, interceptar requisições e verificar o estado da interface. A estratégia pode usar APIs reais ou controladas.',example:'Exemplo: preencher login, clicar em Entrar e verificar que o dashboard foi exibido.',due:today(),interval:0},
 {id:88,subject:'Angular',topic:'Arquitetura',question:'O que são Micro Frontends (MFE)?',answer:'Uma abordagem arquitetural que divide o Front-end em partes independentes por domínio ou feature.',explanation:'Cada MFE pode ter maior autonomia de desenvolvimento e entrega, mas a arquitetura precisa coordenar integração, experiência visual, comunicação e dependências.',example:'Exemplo: checkout e área do cliente podem ser aplicações separadas integradas por um shell.',due:today(),interval:0},
 {id:89,subject:'Angular',topic:'Arquitetura',question:'O que é Module Federation?',answer:'Uma técnica que permite compartilhar ou carregar módulos entre builds independentes, inclusive em runtime.',explanation:'Module Federation é associado ao ecossistema webpack e pode ser usado para integrar aplicações independentes. Ele é uma técnica, não a definição de Micro Frontend.',example:'Exemplo: um shell pode carregar em runtime um componente exposto por uma aplicação remota.',due:today(),interval:0},
 {id:90,subject:'Angular',topic:'Arquitetura',question:'Qual é a diferença entre Micro Frontend e Module Federation?',answer:'Micro Frontend é uma abordagem arquitetural; Module Federation é uma técnica que pode implementá-la.',explanation:'MFE descreve como dividir responsabilidades do Front-end. Module Federation resolve um aspecto técnico de compartilhamento e carregamento entre builds e não é obrigatório para adotar MFE.',example:'Exemplo: uma empresa pode usar arquitetura MFE com Module Federation ou escolher outra estratégia de integração.',due:today(),interval:0},
 {id:91,subject:'React',topic:'Fundamentos',question:'O que é React e para que ele serve?',answer:'React é uma biblioteca JavaScript usada para construir interfaces de usuário com componentes reutilizáveis.',explanation:'React ajuda a construir interfaces dividindo a tela em componentes menores e reutilizáveis. Em vez de tratar uma página inteira como um bloco único, você pode separar partes como cabeçalho, formulário, card e botão. Quando os dados mudam, React atualiza a interface de acordo com o novo estado.',example:'Exemplo: uma tela de loja pode ser formada por Header, Busca, CardProduto, Carrinho e Footer.',due:today(),interval:0},
 {id:92,subject:'React',topic:'Fundamentos',question:'O que é um componente no React?',answer:'É uma parte reutilizável da interface que pode possuir estrutura, dados e comportamento próprios.',explanation:'Componentes são os blocos de construção de uma aplicação React. Eles permitem dividir uma interface grande em partes menores, mais fáceis de entender, reutilizar e testar. Um componente pode representar desde um simples botão até uma página inteira.',example:'Exemplo: Button, ProductCard e LoginPage podem ser componentes separados.',due:today(),interval:0},
 {id:93,subject:'React',topic:'Fundamentos',question:'O que é um Functional Component no React?',answer:'É um componente criado com uma função JavaScript que retorna a interface, normalmente usando JSX.',explanation:'Functional Components são a forma moderna e mais comum de criar componentes React. A função pode receber props, utilizar Hooks e retornar a estrutura que deve aparecer na tela.',example:'Código: function Saudacao() { return <h1>Olá!</h1>; }',due:today(),interval:0},
 {id:94,subject:'React',topic:'Fundamentos',question:'O que é um Class Component no React?',answer:'É um componente criado com uma classe JavaScript que estende React.Component e implementa render().',explanation:'Class Components eram muito usados antes dos Hooks. Eles trabalham com classes, this, state e métodos de ciclo de vida. Continuam suportados, mas novos códigos normalmente usam Functional Components.',example:'Código: class Saudacao extends React.Component { render() { return <h1>Olá!</h1>; } }',due:today(),interval:0},
 {id:95,subject:'React',topic:'Fundamentos',question:'Qual é a diferença entre Functional Components e Class Components?',answer:'Functional Components usam funções e Hooks; Class Components usam classes, this e APIs de ciclo de vida.',explanation:'Os dois modelos criam componentes React, mas possuem estruturas diferentes. Hoje, componentes funcionais são o padrão mais comum porque trabalham diretamente com Hooks como useState e useEffect e costumam resultar em código mais simples.',example:'Exemplo: estado em função usa useState; em classe normalmente usa this.state e this.setState.',due:today(),interval:0},
 {id:96,subject:'React',topic:'Fundamentos',question:'O que é JSX?',answer:'É uma sintaxe que permite escrever estruturas parecidas com HTML dentro do JavaScript.',explanation:'JSX facilita descrever a interface de um componente. Apesar de parecer HTML, ele faz parte do código JavaScript e permite inserir expressões usando chaves.',example:"Código: const nome='Ana'; return <h1>Olá, {nome}</h1>;",due:today(),interval:0},
 {id:97,subject:'React',topic:'Fundamentos',question:'Por que componentes React começam com letra maiúscula?',answer:'Para o React diferenciar componentes próprios de elementos HTML nativos.',explanation:'Nomes iniciados com letra minúscula são tratados como tags HTML, como button ou div. Nomes iniciados com letra maiúscula são interpretados como componentes React criados pela aplicação.',example:'Exemplo: <button /> é HTML; <Button /> representa um componente React.',due:today(),interval:0},
 {id:98,subject:'React',topic:'Fundamentos',question:'Como utilizar um componente dentro de outro componente?',answer:'Renderizando o componente filho como uma tag JSX dentro do componente pai.',explanation:'React incentiva composição: componentes maiores são construídos combinando componentes menores. Isso permite reutilizar partes da interface sem repetir implementação.',example:'Código: function Pagina() { return <Botao />; }',due:today(),interval:0},
 {id:99,subject:'React',topic:'Props',question:'O que são props no React?',answer:'São dados recebidos por um componente, normalmente enviados por seu componente pai.',explanation:'Props permitem parametrizar componentes. O mesmo componente pode ser utilizado várias vezes recebendo valores diferentes. O componente que recebe uma prop deve tratá-la como somente leitura.',example:"Código: <Saudacao nome='Ana' /> e function Saudacao({nome}) { return <h1>{nome}</h1>; }",due:today(),interval:0},
 {id:100,subject:'React',topic:'Props',question:'Para que servem as props?',answer:'Para enviar dados e configurações a componentes, permitindo reutilizá-los com conteúdos diferentes.',explanation:'Sem props, um componente reutilizado tenderia a exibir sempre as mesmas informações. Com props, o componente mantém a mesma estrutura, mas recebe os dados específicos de cada uso.',example:"Exemplo: <Usuario nome='Ana' /> e <Usuario nome='Maria' /> usam o mesmo componente com dados diferentes.",due:today(),interval:0},
 {id:101,subject:'React',topic:'Props',question:'Um componente pode alterar diretamente suas props?',answer:'Não. Props devem ser tratadas como valores somente leitura dentro do componente que as recebe.',explanation:'O componente pai é responsável pelos valores que envia. O filho pode usar esses dados, mas não deve modificá-los diretamente. Essa regra mantém o fluxo de dados mais previsível.',example:'Exemplo: se nome veio por props, o filho não deve tentar fazer props.nome = outroValor.',due:today(),interval:0},
 {id:102,subject:'React',topic:'Props',question:'Como um componente pai envia dados para um componente filho?',answer:'Passando os dados como props na renderização do componente filho.',explanation:'No fluxo mais comum do React, os dados descem do componente pai para o filho. O pai define uma propriedade e o filho recebe esse valor em seus parâmetros.',example:"Código: <Filho nome='Ana' /> envia a prop nome para o componente Filho.",due:today(),interval:0},
 {id:103,subject:'React',topic:'State',question:'O que é state no React?',answer:'É uma informação do componente que pode mudar e influenciar o que aparece na interface.',explanation:'State representa dados que variam durante o uso da aplicação. Quando ele é atualizado, React pode renderizar novamente o componente para refletir o novo valor na tela.',example:'Exemplo: contador, modal aberto, item selecionado e texto digitado em um formulário podem ser state.',due:today(),interval:0},
 {id:104,subject:'React',topic:'State',question:'Qual é a diferença entre props e state?',answer:'Props vêm de fora do componente; state pertence ao componente e pode ser atualizado por ele.',explanation:'Props são entradas recebidas, normalmente do pai. State representa dados internos que mudam ao longo do tempo. Os dois influenciam a renderização, mas possuem responsabilidades diferentes.',example:"Exemplo: nome='Notebook' pode vir por prop; favoritado=true pode ser um state do componente.",due:today(),interval:0},
 {id:105,subject:'React',topic:'State',question:'Para que serve o useState?',answer:'É um Hook usado para criar e atualizar estado em um Functional Component.',explanation:'useState devolve duas coisas: o valor atual do estado e uma função usada para solicitar sua atualização. Ao atualizar o estado, React agenda uma nova renderização.',example:'Código: const [contador, setContador] = useState(0);',due:today(),interval:0},
 {id:106,subject:'React',topic:'State',question:'O que acontece quando atualizamos um state?',answer:'React agenda uma nova renderização do componente usando o novo estado.',explanation:'A atualização do state informa ao React que a interface pode precisar mudar. O componente é executado novamente e React calcula quais alterações precisam aparecer no DOM.',example:'Exemplo: setContador(2) faz o componente renderizar novamente exibindo o novo valor.',due:today(),interval:0},
 {id:107,subject:'React',topic:'State',question:'Por que não devemos alterar o state diretamente?',answer:'Porque React precisa receber uma atualização de estado para controlar corretamente a nova renderização.',explanation:'Alterar diretamente um objeto ou valor pode fazer React não perceber a mudança da maneira esperada e também quebra o princípio de imutabilidade usado para manter atualizações previsíveis.',example:"Errado: usuario.nome='Ana'. Preferível: setUsuario({...usuario, nome:'Ana'}).",due:today(),interval:0},
 {id:108,subject:'React',topic:'Eventos',question:'O que é um evento no React?',answer:'É uma interação da interface, como clique, digitação, envio de formulário ou mudança de campo.',explanation:'React permite associar funções a eventos da interface. Quando o evento acontece, a função configurada é executada e pode, por exemplo, atualizar um state.',example:'Código: <button onClick={salvar}>Salvar</button>',due:today(),interval:0},
 {id:109,subject:'React',topic:'Eventos',question:'Como atualizar um state quando o usuário clica em um botão?',answer:'Chamando a função de atualização do state dentro do manipulador de clique.',explanation:'O clique executa uma função. Dentro dela, usamos o setter retornado pelo useState. A atualização do state leva React a renderizar novamente a interface com o novo valor.',example:'Código: <button onClick={() => setNumero(numero + 1)}>{numero}</button>',due:today(),interval:0},
 {id:110,subject:'React',topic:'Renderização',question:'O que significa renderizar um componente React?',answer:'Significa executar o componente para descobrir qual interface ele deve representar naquele momento.',explanation:'Em um Functional Component, React chama a função do componente e obtém a descrição da interface que ela retorna. Depois, compara esse resultado com o anterior para aplicar as mudanças necessárias.',example:'Exemplo: se contador muda de 1 para 2, o componente é executado novamente para produzir a interface atualizada.',due:today(),interval:0},
 {id:111,subject:'React',topic:'Renderização',question:'O que pode fazer um componente React renderizar novamente?',answer:'Atualizações de state, novas props, mudanças de contexto e renderizações do componente pai.',explanation:'Um re-render acontece quando React precisa recalcular a saída de um componente. Nem todo re-render significa alteração real no DOM; React ainda compara o resultado para decidir o que precisa mudar.',example:'Exemplo: setContador(2) atualiza o state e provoca uma nova renderização do componente.',due:today(),interval:0},
 {id:112,subject:'React',topic:'Renderização',question:'Renderizar novamente significa recriar toda a página?',answer:'Não. React recalcula a saída do componente e atualiza no DOM apenas o que precisa mudar.',explanation:'Re-render não é o mesmo que recarregar a página. React executa novamente os componentes necessários, compara a nova estrutura com a anterior e aplica mudanças específicas na interface.',example:'Exemplo: alterar um contador não exige recarregar Header, CSS e toda a página no navegador.',due:today(),interval:0},
 {id:113,subject:'React',topic:'Renderização',question:'O que é o Virtual DOM?',answer:'É uma representação em memória da interface usada pelo React para calcular atualizações.',explanation:'React trabalha com uma representação da interface e, após uma mudança, gera uma nova versão para compará-la com a anterior. A partir disso, determina quais mudanças precisam chegar ao DOM real.',example:'Exemplo: se apenas um texto mudou, React pode atualizar somente esse trecho do DOM.',due:today(),interval:0},
 {id:114,subject:'React',topic:'Renderização',question:'O que é Reconciliation no React?',answer:'É o processo usado pelo React para comparar renderizações e decidir como atualizar a interface.',explanation:'Durante a reconciliação, React compara a nova árvore de elementos com a anterior. Tipos de elementos e keys ajudam a determinar quais elementos podem ser reaproveitados e quais precisam ser substituídos.',example:'Exemplo: em uma lista, keys estáveis ajudam React a reconhecer qual item permaneceu, entrou ou saiu.',due:today(),interval:0},
 {id:115,subject:'React',topic:'Renderização',question:'O que é renderização condicional no React?',answer:'É renderizar partes diferentes da interface conforme uma condição JavaScript.',explanation:'Como JSX trabalha junto com JavaScript, podemos usar condições para decidir o que será exibido. Isso é comum para login, loading, erros e permissões.',example:'Código: return logado ? <Dashboard /> : <Login />;',due:today(),interval:0},
 {id:116,subject:'React',topic:'Renderização',question:'Como exibir um componente somente quando uma condição for verdadeira?',answer:'Uma forma comum é usar o operador && dentro do JSX.',explanation:'Quando a condição antes de && é verdadeira, React avalia e renderiza o elemento depois dela. Quando é falsa, aquele elemento não é renderizado.',example:'Código: {logado && <Perfil />}',due:today(),interval:0},
 {id:117,subject:'React',topic:'Listas',question:'Como renderizar uma lista de elementos no React?',answer:'Normalmente usando map() para transformar cada item em um elemento ou componente JSX.',explanation:'map percorre um array e devolve uma nova coleção. Em React, usamos essa transformação para gerar um elemento para cada item de uma lista de dados.',example:'Código: usuarios.map(usuario => <Usuario key={usuario.id} nome={usuario.nome} />)',due:today(),interval:0},
 {id:118,subject:'React',topic:'Listas',question:'Para que serve a propriedade key em uma lista React?',answer:'Para dar uma identidade estável aos itens e ajudar React a acompanhar mudanças entre renderizações.',explanation:'A key ajuda React a saber qual item corresponde a qual elemento quando a lista muda. Isso é importante ao inserir, remover ou reordenar itens.',example:'Código: <Usuario key={usuario.id} /> usa um identificador estável do próprio item.',due:today(),interval:0},
 {id:119,subject:'React',topic:'Listas',question:'Por que usar o índice do array como key pode causar problemas?',answer:'Porque o índice pode mudar quando itens são inseridos, removidos ou reordenados.',explanation:'Se a posição muda, o índice pode passar a identificar outro item. Isso pode fazer React reutilizar incorretamente elementos e estados associados. Uma key estável do dado costuma ser mais segura.',example:'Exemplo: ao remover o primeiro item, todos os índices seguintes mudam; um id do usuário continuaria o mesmo.',due:today(),interval:0},
 {id:120,subject:'React',topic:'Composição',question:'O que significa composição de componentes no React?',answer:'É construir componentes maiores combinando componentes menores.',explanation:'Composição permite montar telas complexas a partir de peças independentes. Em vez de um componente fazer tudo, componentes especializados colaboram para formar a interface.',example:'Exemplo: PaginaProduto pode combinar Header, Produto, Preco, BotaoComprar e Footer.',due:today(),interval:0},
 {id:121,subject:'React',topic:'Composição',question:'Por que dividir uma interface em componentes menores?',answer:'Para melhorar reutilização, manutenção, leitura, testes e separação de responsabilidades.',explanation:'Componentes menores tendem a ser mais simples de entender e reutilizar. Mas a divisão precisa fazer sentido: criar um componente para cada div pode gerar fragmentação desnecessária.',example:'Exemplo: um CardProduto reutilizado em várias telas faz mais sentido do que duplicar toda sua estrutura.',due:today(),interval:0}
 ];
 cards=signal<Card[]>(this.load());
 history=signal<StudyDay[]>(this.loadHistory());
 private learningSeed:StudyDay[]=[
  {date:'2026-10-03',learning:['Padrões de Projeto — padrões criacionais, estruturais e comportamentais','Padrões de Projeto — estudo individual dos 22 padrões clássicos','AWS IA — IA Responsável'],reviews:[]},
  {date:'2026-10-02',learning:['JavaScript — 3.1 — Visão geral e definições','AWS IA — Fundamentos de Machine Learning','Padrões de Projeto — Classificação dos padrões'],reviews:[]}
 ];
 studyError=signal(''); studySaving=signal(false);
 @ViewChild(SubjectManagerComponent) manager?:SubjectManagerComponent;
 syncSubjectNames(names:string[]){this.studySubjects.update(v=>Array.from(new Set([...v,...names])))}
 openTopicForm(name:string){this.syncSubjectNames([name]);this.openStudyForm();this.studySubject.set(name)}
 @HostListener('window:open-study-subject',['$event']) openStudySubject(event:CustomEvent){this.activeTab.set('studyPlan');setTimeout(()=>{const item=this.manager?.subjects().find(s=>s.name===event.detail);if(item)this.manager?.openSubject(item)},0)}
 async renameStudySubject(change:{previous:string;name:string}){const res=await this.api('study_queue?subject=eq.'+encodeURIComponent(change.previous),{method:'PATCH',body:JSON.stringify({subject:change.name})});if(res.ok)this.studyItems.update(v=>v.map(i=>i.subject===change.previous?{...i,subject:change.name}:i));else this.studyError.set('Não foi possível atualizar a matéria dos tópicos.')}
 ngOnInit(){void this.initializeRemoteState();}
 private async initializeRemoteState(){await this.loadRemoteHistory();await this.loadRemoteProgress();await this.loadStudySubjects();await this.loadStudyQueue();}
 private async api(path:string,options:RequestInit={}){return fetch(this.supabaseUrl+'/rest/v1/'+path,{...options,headers:{apikey:this.supabaseKey,Authorization:'Bearer '+this.supabaseKey,'Content-Type':'application/json',Prefer:'return=minimal',...(options.headers||{})}})}
 private async loadStudySubjects(){try{const res=await this.api('study_subjects?select=name&order=created_at.asc');if(res.ok){const rows:any[]=await res.json();if(rows.length)this.studySubjects.set(rows.map(r=>r.name));}}catch{}}
 private async loadStudyQueue(){try{const res=await this.api('study_queue?select=id,title,subject,notes,link,priority,status,completed_at&order=created_at.asc');if(res.ok)this.studyItems.set(await res.json());}catch{}}
 openStudyForm(){this.editingStudyId.set(null);this.studyFormOpen.set(true);this.studyTitle.set('');this.studyNotes.set('');this.studyLink.set('');this.studyPriority.set('media')}
 editStudyItem(item:StudyItem){this.editingStudyId.set(item.id);this.studyTitle.set(item.title);this.studySubject.set(item.subject);this.studyNotes.set(item.notes||'');this.studyLink.set(item.link||'');this.studyPriority.set(item.priority);this.studyFormOpen.set(true)}
 closeStudyForm(){this.studyFormOpen.set(false);this.editingStudyId.set(null)}
 async saveStudyItem(){const title=this.studyTitle().trim();if(!title||this.studySaving())return;this.studySaving.set(true);this.studyError.set('');const payload={title,subject:this.studySubject(),notes:this.studyNotes().trim()||null,link:this.normalizeLink(this.studyLink()),priority:this.studyPriority()};try{const id=this.editingStudyId();const res=await this.api(id?'study_queue?id=eq.'+encodeURIComponent(id):'study_queue',{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(id?payload:{...payload,status:'todo'})});if(!res.ok)throw new Error();const rows:StudyItem[]=await res.json();if(!rows[0])throw new Error();this.studyItems.update(v=>id?v.map(x=>x.id===id?rows[0]:x):[...v,rows[0]]);this.closeStudyForm()}catch{this.studyError.set('Não foi possível salvar o tópico. Tente novamente.')}finally{this.studySaving.set(false)}}

 normalizeLink(value:string){const v=value.trim();if(!v)return null;return /^https?:\/\//i.test(v)?v:'https://'+v}
 async addStudySubject(){const name=this.newSubjectName().trim();if(!name)return;try{const res=await this.api('study_subjects',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name})});if(res.ok){const rows:any[]=await res.json();const saved=rows[0]?.name||name;this.studySubjects.update(v=>v.includes(saved)?v:[...v,saved]);this.studySubject.set(saved);this.newSubjectName.set('');this.subjectFormOpen.set(false);}}catch{}}
 async completeStudyItem(item:StudyItem){if(item.status==='done')return;const completedAt=new Date().toISOString();try{const res=await this.api('study_queue?id=eq.'+encodeURIComponent(item.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'done',completed_at:completedAt})});if(!res.ok)return;this.studyItems.update(v=>v.map(x=>x.id===item.id?{...x,status:'done',completed_at:completedAt}:x));const label=item.subject+' — '+item.title;await this.api('study_activity?on_conflict=activity_date,kind,label',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({activity_date:today(),kind:'learning',label})});await this.loadRemoteHistory();}catch{}}
 todoStudyItems=computed(()=>this.studyItems().filter(x=>x.status==='todo'));
 completedStudyItems=computed(()=>this.studyItems().filter(x=>x.status==='done'));
 private async loadRemoteHistory(){try{const res=await this.api('study_activity?select=activity_date,kind,label&order=activity_date.desc,created_at.asc');if(!res.ok)return;const rows:any[]=await res.json();const days=new Map<string,StudyDay>();for(const row of rows){if(!days.has(row.activity_date))days.set(row.activity_date,{date:row.activity_date,learning:[],reviews:[]});const day=days.get(row.activity_date)!;const target=row.kind==='learning'?day.learning:day.reviews;if(!target.includes(row.label))target.push(row.label);}this.history.set(this.mergeLearning([...days.values()]));}catch{}}
 private async loadRemoteProgress(){try{const res=await this.api('seed_card_progress?select=card_id,due,interval');if(!res.ok)return;const rows:any[]=await res.json();if(rows.length){const map=new Map(rows.map(r=>[Number(r.card_id),r]));this.cards.set(this.cards().map(card=>{const p=map.get(card.id);return p?{...card,due:p.due,interval:Number(p.interval)}:card;}));localStorage.setItem('flashcards',JSON.stringify(this.cards()));}else{this.restoreCompletedReviewsFromHistory();}}catch{}}
 private restoreCompletedReviewsFromHistory(){const reviewedToday=this.history().find(d=>d.date===today())?.reviews||[];if(!reviewedToday.length)return;const next=this.cards().map(card=>{const name=card.subject==='AWS'?'AWS IA':card.subject;const full=`${name} — ${card.topic}`;const completed=reviewedToday.includes(name)||reviewedToday.includes(full);return completed&&card.due<=today()?{...card,due:addDays(1),interval:1}:card;});this.cards.set(next);localStorage.setItem('flashcards',JSON.stringify(next));for(const card of next.filter(x=>x.due===addDays(1)&&x.interval===1))void this.saveRemoteProgress(card,'restored');}
 private saveRemoteProgress(card:Card,rating:string){return this.api('seed_card_progress?on_conflict=card_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({card_id:card.id,due:card.due,interval:card.interval,rating,last_reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});}
 private loadHistory():StudyDay[]{return this.learningSeed;}
 private mergeLearning(saved:StudyDay[]):StudyDay[]{const result=saved.map(d=>({...d,learning:[...d.learning],reviews:[...d.reviews]}));for(const seedDay of this.learningSeed){const found=result.find(d=>d.date===seedDay.date);if(found){found.learning=Array.from(new Set([...found.learning,...seedDay.learning]));}else result.push({...seedDay,learning:[...seedDay.learning],reviews:[]});}return result.sort((a,b)=>b.date.localeCompare(a.date));}
 private saveReview(label:string){const date=today();const next=this.history().map(d=>({...d,learning:[...d.learning],reviews:[...d.reviews]}));let day=next.find(d=>d.date===date);if(!day){day={date,learning:[],reviews:[]};next.push(day);}if(!day.reviews.includes(label))day.reviews.push(label);next.sort((a,b)=>b.date.localeCompare(a.date));this.history.set(next);void this.api('study_activity?on_conflict=activity_date,kind,label',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({activity_date:date,kind:'review',label})});}
 reviewLabel(){const subject=this.subject();const topic=this.topic();const name=subject==='AWS'?'AWS IA':subject||'';return topic==='Todos'?name:`${name} — ${topic}`;}
 formatDate(date:string){const [y,m,d]=date.split('-');return `${d}/${m}/${y}`;}
 subjectCards=computed(()=>this.subject()?this.cards().filter(c=>c.subject===this.subject()):[]);
 topics=computed(()=>['Todos',...Array.from(new Set(this.subjectCards().map(c=>c.topic)))]);
 dueCards=computed(()=>this.shuffle(this.subjectCards().filter(c=>c.due<=today()&&(this.topic()==='Todos'||c.topic===this.topic()))));
 totalDue=computed(()=>this.cards().filter(c=>c.due<=today()).length);
 subjectDue=(subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java')=>this.cards().filter(c=>c.subject===subject&&c.due<=today()).length;
 subjectTotal=(subject:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java')=>this.cards().filter(c=>c.subject===subject).length;
 subjectIcon(subject:string){return ({AWS:'☁',JavaScript:'JS','Padrões de Projeto':'▱',Angular:'A',React:'⚛',Arquitetura:'⌂',Java:'☕'} as Record<string,string>)[subject]||'•';}
 monthLabel=computed(()=>this.historyMonth().toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,v=>v.toUpperCase()));
 calendarDays=computed(()=>{const base=this.historyMonth();const y=base.getFullYear(),m=base.getMonth();const first=new Date(y,m,1);const last=new Date(y,m+1,0);const cells:Array<{date:string|null;day:number|null;learning:boolean;review:boolean;today:boolean}> = [];for(let i=0;i<first.getDay();i++)cells.push({date:null,day:null,learning:false,review:false,today:false});for(let d=1;d<=last.getDate();d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const activity=this.history().find(x=>x.date===key);cells.push({date:key,day:d,learning:!!activity?.learning.length,review:!!activity?.reviews.length,today:key===today()});}return cells;});
 selectedHistoryDay=computed(()=>this.history().find(d=>d.date===this.selectedHistoryDate())||null);
 studyDaysInMonth=computed(()=>{const y=this.historyMonth().getFullYear(),m=this.historyMonth().getMonth();return this.history().filter(d=>{const dt=new Date(d.date+'T12:00:00');return dt.getFullYear()===y&&dt.getMonth()===m&&(d.learning.length||d.reviews.length)}).length;});
 changeHistoryMonth(offset:number){const d=this.historyMonth();this.historyMonth.set(new Date(d.getFullYear(),d.getMonth()+offset,1));this.selectedHistoryDate.set(null)}
 selectHistoryDate(date:string|null){if(date)this.selectedHistoryDate.set(date)}
 setTab(tab:'home'|'studyPlan'|'progress'|'history'|'settings'){this.activeTab.set(tab);if(tab==='history'&&!this.selectedHistoryDate()){const latest=this.history().find(d=>d.learning.length||d.reviews.length);if(latest){const dt=new Date(latest.date+'T12:00:00');this.historyMonth.set(new Date(dt.getFullYear(),dt.getMonth(),1));}}}
 card=computed(()=>this.dueCards()[this.index()%Math.max(this.dueCards().length,1)]);
 progress=computed(()=>this.dueCards().length?String(this.index()+1)+' / '+String(this.dueCards().length):'0 / 0');
 private shuffle<T>(items:T[]):T[]{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
 private load():Card[]{try{
  const saved:Card[]=JSON.parse(localStorage.getItem('flashcards')||'null');
  if(!Array.isArray(saved))return this.seed;
  return this.seed.map(seedCard=>{
   const previous=saved.find(card=>card.question===seedCard.question);
   return previous?{...seedCard,due:previous.due,interval:previous.interval}:seedCard;
  });
 }catch{return this.seed}}
 openSubject(v:'AWS'|'JavaScript'|'Padrões de Projeto'|'Angular'|'React'|'Arquitetura'|'Java'){this.subject.set(v);this.topic.set('Todos');this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
 back(){this.subject.set(null);this.topic.set('Todos');this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false);this.activeTab.set('home')}
 choose(v:string){this.topic.set(v);this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
 reveal(){this.flipped.set(!this.flipped());this.explanationOpen.set(false)}
 toggleExplanation(){this.explanationOpen.set(!this.explanationOpen())}
 rate(r:Rating){const c=this.card();if(!c)return;const days={again:1,hard:2,good:4,easy:7}[r];const currentDeck=this.dueCards().map(x=>x.id);const updated={...c,due:addDays(days),interval:days};this.cards.set(this.cards().map(x=>x.id===c.id?updated:x));localStorage.setItem('flashcards',JSON.stringify(this.cards()));void this.saveRemoteProgress(updated,r);const remaining=this.cards().filter(x=>currentDeck.includes(x.id)&&x.due<=today()).length;if(remaining===0)this.saveReview(this.reviewLabel());this.flipped.set(false);this.explanationOpen.set(false);this.index.set(0)}
 reset(){localStorage.removeItem('flashcards');this.cards.set(this.seed);this.index.set(0);this.flipped.set(false);this.explanationOpen.set(false)}
}