import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { loadEnvFile } from "node:process";

export function readPublicConfig(env) {
  const required = (name) => {
    const value = env[name]?.trim();
    if (!value)
      throw new Error(
        `Configure ${name} no ambiente ou no arquivo .env (consulte .env.example).`,
      );
    return value;
  };
  const httpUrl = (name) => {
    const value = required(name);
    const url = new URL(value);
    if (
      !["https:", "http:"].includes(url.protocol) ||
      url.username ||
      url.password
    ) {
      throw new Error(`${name} deve ser uma URL HTTP(S) sem credenciais.`);
    }
    return value;
  };
  const key = required("SUPABASE_PUBLISHABLE_KEY");
  // Only public frontend keys belong in the generated bundle.
  const claims = key.startsWith("eyJ")
    ? JSON.parse(Buffer.from(key.split(".")[1], "base64url").toString())
    : null;
  if (!key.startsWith("sb_publishable_") && claims?.role !== "anon") {
    throw new Error(
      "SUPABASE_PUBLISHABLE_KEY deve ser uma chave pública publishable ou anon.",
    );
  }
  const date = required("APP_PRIVACY_UPDATED_AT");
  if (
    !/^\d{4}-\d{2}-\d{2}$/.test(date) ||
    new Date(date).toISOString().slice(0, 10) !== date
  ) {
    throw new Error(
      "APP_PRIVACY_UPDATED_AT deve ser uma data válida YYYY-MM-DD.",
    );
  }
  return {
    supabaseUrl: httpUrl("SUPABASE_URL"),
    supabasePublishableKey: key,
    ownerName: required("APP_OWNER_NAME"),
    supportUrl: httpUrl("APP_SUPPORT_URL"),
    privacyUpdatedAt: date,
  };
}

if (process.argv[1]?.endsWith("configure.mjs")) {
  if (existsSync(".env")) loadEnvFile(".env");
  const config = readPublicConfig(process.env);
  const output = "src/app/app-config.generated.ts";
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(
    output,
    `// Generated by npm run configure. Do not commit installation values.\nexport const appConfig = ${JSON.stringify(config, null, 2)} as const;\n`,
  );
  console.log("Configuração pública validada.");
}
